// ksaDataService.js
// Phase 2 scaffolding: core infrastructure for the ASP → JSON.txt static-file migration.
// Phase 3 will add one fetch*() endpoint function per endpointimplementation order entry.
//
// Dependencies (must be loaded before this file):
//   helpFuncs.js  — provides dbResponse(), handleError()
//   ksaGlobals.js — provides KSA_UI_STATE.dataLoadQueue

// Wrap in an IIFE so internal helpers stay private; expose only the public API.
const KSA_DATA_SERVICE = (function () {
  'use strict';

  // ===========================================================================
  // CONSTANTS
  // ===========================================================================

  // Root-relative path to the JSON.txt file tree generated by convert_mdb_to_json.py.
  const DATABASE_ROOT      = 'database/';
  // New-format JSON.txt files (proper types + pre-structured fields) generated
  // by the updated convert_mdb_to_json.py (Phase 1).  Converted fetch* functions
  // read from this root; unconverted functions continue using DATABASE_ROOT.
  const DATABASE_JSON_ROOT = 'databaseJSON/';

  // Parity-test debug logging.
  // Set  window.KSA_DS_DEBUG = true  in the browser console (before or after page load)
  // to log the assembled response string for each endpoint so it can be diffed against
  // the captured ASP response.  Usage:
  //   KSA_DS_DEBUG = true   ← enable
  //   KSA_DS_DEBUG = false  ← disable
  function _parity(label, responseText) {
    if (window.KSA_DS_DEBUG) {
      console.groupCollapsed('[KSA_DS parity] ' + label);
      console.log(responseText);
      console.groupEnd();
    }
  }

  // ===========================================================================
  // CACHE MAPS
  // ===========================================================================

  // Index cache: Map<entityId, indexObject>
  // indexObject keys are recordset folder names, values are sorted UT arrays.
  // e.g. { craftdata: [0, 28800], flightdata: [0, 28800, 57600], ... }
  const _indexCache = new Map();

  // Response cache: Map<url, parsedData>
  // Covers both UT-split record objects and bulk array files.
  // Keyed by the canonical URL (without cache-bust query string).
  const _responseCache = new Map();

  // In-flight deduplicator: Map<url, Promise<parsedData>>
  // Prevents duplicate concurrent fetch() calls for the same file.
  const _inFlight = new Map();

  // ===========================================================================
  // PRIVATE HELPERS
  // ===========================================================================

  // Returns "YYYY-MM-DD" so same-day requests share the browser cache but the
  // cache refreshes automatically the following day (mirrors loadJsonTxt behaviour).
  function _dateBust() {
    return new Date().toISOString().split('T')[0];
  }

  // ===========================================================================
  // PUBLIC API — CORE DATA UTILITIES
  // ===========================================================================

  /**
   * seekToUT(utArray, targetUT)
   *
   * Binary search: returns the largest UT value in a sorted ascending array that
   * is <= targetUT.  Replicates the ASP MoveLast/MovePrevious loop used across
   * all UT-seeking endpoints.
   *
   * If every element is > targetUT the first element is returned (mirrors ASP
   * behaviour where MovePrevious past BOF calls MoveNext back to first record).
   *
   * @param {number[]} utArray   Sorted ascending array of UT timestamps.
   * @param {number}   targetUT  The game-time UT to search for.
   * @returns {number|null}      Matching UT, or null if the array is empty.
   */
  function seekToUT(utArray, targetUT) {
    if (!utArray || !utArray.length) return null;
    var lo = 0, hi = utArray.length - 1, result = utArray[0];
    while (lo <= hi) {
      var mid = (lo + hi) >>> 1;
      if (utArray[mid] <= targetUT) {
        result = utArray[mid];
        lo = mid + 1;
      } else {
        hi = mid - 1;
      }
    }
    return result;
  }

  /**
   * getNextUT(utArray, targetUT)
   *
   * Binary search: returns the smallest UT value in a sorted ascending array
   * that is strictly > targetUT.  Used to pre-cache the next record boundary
   * (the "future data" the ASP endpoints also read ahead for).
   *
   * @param {number[]} utArray   Sorted ascending array of UT timestamps.
   * @param {number}   targetUT  The current game-time UT.
   * @returns {number|null}      The next UT after targetUT, or null if there are none.
   */
  function getNextUT(utArray, targetUT) {
    if (!utArray || !utArray.length) return null;
    var lo = 0, hi = utArray.length - 1, result = null;
    while (lo <= hi) {
      var mid = (lo + hi) >>> 1;
      if (utArray[mid] > targetUT) {
        result = utArray[mid];
        hi = mid - 1;
      } else {
        lo = mid + 1;
      }
    }
    return result;
  }

  /**
   * fetchJson(url)
   *
   * fetch() + JSON.parse() wrapper with:
   *   - Response caching  (no re-download for the lifetime of the page)
   *   - In-flight deduplication (concurrent callers share one pending fetch)
   *   - Date-based cache-busting (daily cache refresh; same-day requests reuse
   *     the browser HTTP cache — identical to loadJsonTxt's strategy)
   *
   * NOTE: loadJsonTxt() is intentionally reserved for the multi-object social
   * archive format; this function is used for all database JSON.txt files.
   *
   * @param {string} url  Relative or absolute path to the .json.txt file.
   * @returns {Promise}   Resolves to the parsed JSON value (object, array, …).
   */
  function fetchJson(url) {
    // Serve from in-memory cache on repeated calls.
    if (_responseCache.has(url)) {
      return Promise.resolve(_responseCache.get(url));
    }
    // Return the existing promise if a fetch is already in progress.
    if (_inFlight.has(url)) {
      return _inFlight.get(url);
    }

    var sep = url.indexOf('?') !== -1 ? '&' : '?';
    var fullUrl = url + sep + '_=' + _dateBust();

    var promise = fetch(fullUrl)
      .then(function (resp) {
        if (!resp.ok) {
          throw new Error('HTTP ' + resp.status + ' loading: ' + url);
        }
        return resp.text();
      })
      .then(function (text) {
        var data = JSON.parse(text);
        _responseCache.set(url, data);
        _inFlight.delete(url);
        return data;
      })
      ['catch'](function (err) {        // bracket notation avoids IE8 reserved-word parse error
        _inFlight.delete(url);
        throw err;
      });

    _inFlight.set(url, promise);
    return promise;
  }

  /**
   * objToRs(obj)
   *
   * Inverse of rsToObj() in helpFuncs.js.
   * Converts a plain object to the ASP-style delimited record string that the
   * existing AJAX callbacks (loadBodyAJAX, loadPartsAJAX, …) already know how
   * to parse — producing zero front-end display changes.
   *
   * Format:  "Field~value`Field2~value2`Field3~value3"
   *   - Fields are separated by backtick (`)
   *   - No trailing backtick (mirrors ASP's left(record, len(record)-1))
   *   - Null/undefined values produce "Field~" (empty after the ~)
   *   - Boolean values produce "Field~true" / "Field~false"
   *   - All other values are coerced to string via String()
   *
   * @param {Object|null} obj  Plain object with DB field names as keys.
   * @returns {string}
   */
  function objToRs(obj) {
    if (!obj) return '';
    var parts = [];
    Object.keys(obj).forEach(function (key) {
      // Mirrors ASP's replace(field.name, " ", "") — strip spaces from column names.
      var fieldName = key.replace(/ /g, '');
      var val = obj[key];
      if (val === null || val === undefined) {
        parts.push(fieldName + '~');
      } else {
        parts.push(fieldName + '~' + String(val));
      }
    });
    return parts.join('`');
  }

  /**
   * invokeCallback(label, callback, responseText, data)
   *
   * Simulates a completed loadDB() call so that existing AJAX callbacks receive
   * the same mock-xhttp object they expect and KSA_UI_STATE.dataLoadQueue is
   * managed identically to a real XMLHttpRequest round-trip.
   *
   * Delegates to dbResponse() (from helpFuncs.js) so queue removal and error
   * handling are both handled by the same code path as real AJAX.
   *
   * @param {string}   label        Descriptive label pushed onto dataLoadQueue
   *                                (takes the place of the ASP URL).
   * @param {function} callback     The existing AJAX callback (receives (xhttp, data)).
   * @param {string}   responseText The fully assembled delimited string.
   * @param {*}        [data]       Optional pass-through value (same as loadDB's third arg).
   */
  function invokeCallback(label, callback, responseText, data) {
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    dbResponse({ responseText: responseText }, label, callback, data);
  }

  /**
   * _trackAndInvoke(label, callback, result, data)
   *
   * New-convention counterpart to invokeCallback() for converted fetch*
   * functions (Phase 3+).  Manages KSA_UI_STATE.dataLoadQueue identically
   * (so the loading indicator still works) but delivers the structured result
   * object directly to the callback — no mock xhttp, no responseText parsing.
   *
   * New callback signature:
   *   callback(result, data)   // result = structured JS object, data = pass-through
   *
   * Both invokeCallback and _trackAndInvoke coexist until all callbacks are
   * converted in Phase 3.
   *
   * @param {string}   label     Descriptive label pushed onto dataLoadQueue.
   * @param {function} callback  Converted AJAX callback (receives (result, data)).
   * @param {*}        result    Structured JS object produced by the fetch* function.
   * @param {*}        [data]    Optional pass-through value (same role as loadDB's third arg).
   */
  function _trackAndInvoke(label, callback, result, data) {
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    // Remove the label from the queue (mirrors dbResponse's queue management)
    // then invoke the callback synchronously with the result object.
    var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
    if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
    try {
      callback(result, data);
    } catch (err) {
      handleError(err, label, true);
    }
  }

  // ===========================================================================
  // PUBLIC API — PATH HELPERS
  // ===========================================================================

  /**
   * indexPath(entityId)
   * URL to the index file for a craft or kerbal entity.
   * e.g. indexPath('jeb') → 'database/jeb/jeb_index.json.txt'
   */
  function indexPath(entityId) {
    return DATABASE_ROOT + entityId + '/' + entityId + '_index.json.txt';
  }

  /**
   * dbFilePath(entityId, recordset, ut)
   * URL to a specific UT-split record file.
   * e.g. dbFilePath('jeb', 'stats', 12345) → 'database/jeb/stats/jeb_stats_12345.json.txt'
   */
  function dbFilePath(entityId, recordset, ut) {
    return DATABASE_ROOT + entityId + '/' + recordset + '/' +
           entityId + '_' + recordset + '_' + ut + '.json.txt';
  }

  /**
   * bulkFilePath(entityId, recordset)
   * URL to a bulk (non-UT-split) data file loaded all at once.
   * e.g. bulkFilePath('jeb', 'missions') → 'database/jeb/jeb_missions.json.txt'
   */
  function bulkFilePath(entityId, recordset) {
    return DATABASE_ROOT + entityId + '/' + entityId + '_' + recordset + '.json.txt';
  }

  /**
   * catalogFilePath(name)
   * URL to a _Catalogs file.
   * e.g. catalogFilePath('bodies') → 'database/_Catalogs/bodies.json.txt'
   */
  function catalogFilePath(name) {
    return DATABASE_ROOT + '_Catalogs/' + name + '.json.txt';
  }

  /**
   * flightFilePath(flightId, recordset)
   * URL to a _Flights data file (dbFlt* databases).
   * e.g. flightFilePath('someFlight', 'missiondata')
   *        → 'database/_Flights/someFlight/someFlight_missiondata.json.txt'
   */
  function flightFilePath(flightId, recordset) {
    return DATABASE_ROOT + '_Flights/' + flightId + '/' +
           flightId + '_' + recordset + '.json.txt';
  }

  // ---------------------------------------------------------------------------
  // JSON path helpers — parallel set using DATABASE_JSON_ROOT.
  // Used exclusively by converted fetch* functions (Phase 3+).
  // ---------------------------------------------------------------------------

  /**
   * jsonIndexPath(entityId)
   * e.g. jsonIndexPath('jeb') → 'databaseJSON/jeb/jeb_index.json.txt'
   */
  function jsonIndexPath(entityId) {
    return DATABASE_JSON_ROOT + entityId + '/' + entityId + '_index.json.txt';
  }

  /**
   * jsonDbFilePath(entityId, recordset, ut)
   * e.g. jsonDbFilePath('jeb', 'stats', 12345) → 'databaseJSON/jeb/stats/jeb_stats_12345.json.txt'
   */
  function jsonDbFilePath(entityId, recordset, ut) {
    return DATABASE_JSON_ROOT + entityId + '/' + recordset + '/' +
           entityId + '_' + recordset + '_' + ut + '.json.txt';
  }

  /**
   * jsonBulkFilePath(entityId, recordset)
   * e.g. jsonBulkFilePath('jeb', 'missions') → 'databaseJSON/jeb/jeb_missions.json.txt'
   */
  function jsonBulkFilePath(entityId, recordset) {
    return DATABASE_JSON_ROOT + entityId + '/' + entityId + '_' + recordset + '.json.txt';
  }

  /**
   * jsonCatalogFilePath(name)
   * e.g. jsonCatalogFilePath('bodies') → 'databaseJSON/_Catalogs/bodies.json.txt'
   */
  function jsonCatalogFilePath(name) {
    return DATABASE_JSON_ROOT + '_Catalogs/' + name + '.json.txt';
  }

  /**
   * jsonFlightFilePath(flightId, recordset)
   * e.g. jsonFlightFilePath('someFlight', 'missiondata')
   *        → 'databaseJSON/_Flights/someFlight/someFlight_missiondata.json.txt'
   */
  function jsonFlightFilePath(flightId, recordset) {
    return DATABASE_JSON_ROOT + '_Flights/' + flightId + '/' +
           flightId + '_' + recordset + '.json.txt';
  }

  // ===========================================================================
  // PUBLIC API — INDEX MANAGEMENT
  // ===========================================================================

  /**
   * loadIndex(entityId)
   *
   * Loads and caches the index file for a craft or kerbal entity (once per page
   * load).  Subsequent calls for the same entityId are served from the index
   * cache with no network round-trip.
   *
   * The index object maps recordset folder names to sorted UT arrays:
   *   { craftdata: [0, 28800], flightdata: [0, 28800, 57600], ... }
   *
   * @param {string} entityId  Craft DB name or kerbal ID (lowercase).
   * @returns {Promise<Object>}
   */
  function loadIndex(entityId) {
    if (_indexCache.has(entityId)) {
      return Promise.resolve(_indexCache.get(entityId));
    }
    return fetchJson(indexPath(entityId)).then(function (index) {
      _indexCache.set(entityId, index);
      return index;
    });
  }

  // ===========================================================================
  // PHASE 3 HELPERS
  // ===========================================================================

  /**
   * _normalizeStatsRecord(stats)
   *
   * Coerces Dockings and TEVA to proper integers.
   * Older DB exports serialized zero values as the string "0" rather than the
   * integer 0.  String "0" is truthy in JS, which would cause the conditional
   * display guards in ksaCrewOps.js to incorrectly show empty rows.
   * Operates in-place; safe to call with null/undefined.
   */
  function _normalizeStatsRecord(stats) {
    if (!stats) return;
    if (stats.Dockings !== null && stats.Dockings !== undefined) stats.Dockings = +stats.Dockings || 0;
    if (stats.TEVA     !== null && stats.TEVA     !== undefined) stats.TEVA     = +stats.TEVA     || 0;
  }

  /**
   * _normalizeKeys(obj)
   *
   * Returns a shallow copy of obj with all spaces removed from key names.
   * e.g. "Orbital Period" → "OrbitalPeriod", "SOI Event" → "SOIEvent".
   * Returns null/undefined unchanged.
   */
  function _normalizeKeys(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    var normalized = {};
    Object.keys(obj).forEach(function (key) {
      normalized[key.replace(/ /g, '')] = obj[key];
    });
    return normalized;
  }

  // ===========================================================================
  // PHASE 3 ENDPOINT IMPLEMENTATIONS
  // ===========================================================================

  // ---------------------------------------------------------------------------
  // Endpoint #1 — replaces loadBodyData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchBodyData(callback)
   *
   * Loads all planet and moon records from the merged bodies catalog and delivers
   * them to loadBodyAJAX as a native array of body objects.
   *
   * @param {function} callback  loadBodyAJAX — receives (bodies[]).
   */
  function fetchBodyData(callback) {
    var label = 'loadBodyData.asp';
    fetchJson(jsonCatalogFilePath('bodies'))
      .then(function(records) {
        _trackAndInvoke(label, callback, records);
      })
      ['catch'](function(err) {
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #2 — replaces loadPartsData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchPartsData(callback)
   *
   * Loads all parts records from the parts catalog and delivers them to
   * loadPartsAJAX as a native array of part objects.
   *
   * @param {function} callback  loadPartsAJAX — receives (parts[]).
   */
  function fetchPartsData(callback) {
    var label = 'loadPartsData.asp';
    fetchJson(jsonCatalogFilePath('parts'))
      .then(function(records) {
        _trackAndInvoke(label, callback, records);
      })
      ['catch'](function(err) {
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #3 — replaces loadAscentData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchAscentData(db, callback)
   *
   * Loads all rows from the ascent data bulk file for a given craft and delivers
   * them to the existing loadAscentAJAX callback in the same pipe-delimited
   * format that loadAscentData.asp produced.
   *
   * ASP logic replicated:
   *   - Dump all records from the [ascent data] table.
   *   - Apply replace(field.name, " ", "") to strip spaces from field names
   *     (the only affected field is "Total Fuel" → "TotalFuel").
   *   - Join records with "|" — no trailing "|" (loadAscentAJAX does not
   *     filter empty strings after splitting, so a trailing delimiter would
   *     push a spurious empty object into ops.ascentData.telemetry).
   *
   * The bulk file is cached after the first fetch so repeated calls (e.g.
   * if the user navigates away and back to the same vessel) are free.
   *
   * @param {string}   db        Craft DB name (e.g. "ascensionmk2-2").
   * @param {function} callback  Existing AJAX callback (loadAscentAJAX).
   */
  function fetchAscentData(db, callback) {
    var label = 'loadAscentData.asp?db=' + db;
    fetchJson(jsonBulkFilePath(db, 'ascentdata'))
      .then(function (records) {
        // The "Total Fuel" column in the MDB contains a space in its name.
        // Normalize all keys by stripping spaces so consumers can read .TotalFuel.
        var normalized = records.map(function(obj) {
          var out = {};
          Object.keys(obj).forEach(function(k) { out[k.replace(/ /g, '')] = obj[k]; });
          return out;
        });
        _trackAndInvoke(label, callback, normalized);
      })
      ['catch'](function (err) {
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #4 — replaces loadMapData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchMapData(refID, callback)
   *
   * Loads map data from the JSON maps catalog and delivers a structured result
   * directly to the callback via _trackAndInvoke (no rsToObj / xhttp).
   *
   * Two modes:
   *   refID === -1  — result is the full records[] array (loadSurfaceUpdatesAJAX).
   *   refID number  — result is the single matching object, or null if not found
   *                   (loadMapDataAJAX).
   *
   * The maps catalog is fetched only once; the fetchJson cache serves
   * subsequent calls (per-body loads) with zero extra network round-trips.
   *
   * @param {number}   refID     -1 for all records, or the numeric body RefID.
   * @param {function} callback  loadSurfaceUpdatesAJAX (refID=-1) or
   *                             loadMapDataAJAX (specific body).
   *                             Receives (result) — a records[] or single object.
   */
  function fetchMapData(refID, callback) {
    var label = 'loadMapData.asp?refID=' + refID;
    fetchJson(jsonCatalogFilePath('maps'))
      .then(function (records) {
        var result;
        if (refID === -1) {
          result = (records && records.length) ? records : null;
        } else {
          result = null;
          for (var i = 0; i < records.length; i++) {
            if (records[i].RefID === refID) { result = records[i]; break; }
          }
        }
        _trackAndInvoke(label, callback, result);
      })
      ['catch'](function (err) {
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #5 — replaces loadFltData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchFltData(name, callback)
   *
   * Loads mission data (single record) and flight data (full array) for an
   * aircraft-type flight from the _Flights folder, then delivers a structured
   * result object directly to loadFltDataAJAX via _trackAndInvoke.
   *
   * Result shape: { mission: obj, flightData: sampledRows[], name: str }
   *
   * Flight data is sampled every 5th row (matching ASP's rsFlightData.move 5)
   * to limit memory usage for long flights. The full-resolution array is never
   * held in memory after the Promise resolves.
   *
   * Both files are cached by fetchJson() after the first load, so subsequent
   * calls for the same flight (e.g. multi-flight loads) are served from memory.
   *
   * @param {string}   name      Flight DB name (e.g. "Deuce1-22-19").
   * @param {function} callback  loadFltDataAJAX — receives (result).
   */
  function fetchFltData(name, callback) {
    var label = 'loadFltData.asp?data=' + name;
    Promise.all([
      fetchJson(jsonFlightFilePath(name, 'missiondata')),
      fetchJson(jsonFlightFilePath(name, 'flightdata'))
    ]).then(function (results) {
      var mission    = results[0];   // plain object (single-record table)
      var allRows    = results[1];   // array of all flight data records

      // Sample every 5th row, mirroring ASP's rsFlightData.move 5.
      var flightData = [];
      for (var i = 0; i < allRows.length; i += 5) {
        flightData.push(allRows[i]);
      }

      _trackAndInvoke(label, callback, { mission: mission, flightData: flightData, name: name });
    })
    ['catch'](function (err) {
      handleError(err, label, true);
    });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #6 — replaces loadMenuData.asp
  // ---------------------------------------------------------------------------

  /**
   * _buildMenuCraftRecord(vessel, ut)
   *
   * Private helper used only by fetchMenuData.
   * Reads pre-structured JSON fields (Phase 1 format) and returns a typed
   * vessel entry object for loadMenuAJAX, or null when ref === -2.
   *
   * start default (MissionStartTime is null): FIRST SOI entry ut.
   * end default   (MissionEnd is null):       LAST  SOI entry ut.
   * bodyRef: second-to-last SOI entry's ref (last non-inactive body reference).
   */
  function _buildMenuCraftRecord(vessel, ut) {
    // Determine current SOI ref from pre-structured array [{ut, ref}, ...].
    var soi = vessel.SOI;
    var ref = -2;
    for (var i = 0; i < soi.length; i++) {
      if (soi[i].ut <= ut) ref = soi[i].ref;
      else break;
    }

    // ref === -2 → vessel is completely removed from both menu lists.
    if (ref === -2) return null;

    // Derive default times from SOI array.
    var firstSoiUT = soi[0].ut;
    var lastSoiUT  = soi[soi.length - 1].ut;

    var start = (vessel.MissionStartTime !== null && vessel.MissionStartTime !== undefined)
      ? vessel.MissionStartTime
      : firstSoiUT;

    var end = (vessel.MissionEnd !== null && vessel.MissionEnd !== undefined)
      ? vessel.MissionEnd.utEnd
      : lastSoiUT;

    // Compute current name from pre-structured Vessel field.
    // If it's an array [{ut, name}], find the last entry whose ut <= current UT.
    // If it's a plain string, use it directly.
    var name, names;
    if (Array.isArray(vessel.Vessel)) {
      names = vessel.Vessel;
      name  = names[0].name;
      for (var ni = 0; ni < names.length; ni++) {
        if (names[ni].ut === null || names[ni].ut <= ut) name = names[ni].name;
        else break;
      }
    } else {
      name  = vessel.Vessel;
      names = null;
    }

    // Compute current type from pre-structured Type field (same pattern).
    var type;
    if (Array.isArray(vessel.Type)) {
      type = vessel.Type[0].type;
      for (var ti = 0; ti < vessel.Type.length; ti++) {
        if (vessel.Type[ti].ut === null || vessel.Type[ti].ut <= ut) type = vessel.Type[ti].type;
        else break;
      }
    } else {
      type = vessel.Type;
    }

    // bodyRef: second-to-last SOI entry's ref (the last body before going inactive).
    var bodyRef = 3;
    if (soi.length > 1) bodyRef = soi[soi.length - 2].ref;

    // Program and vessel-patch names from pre-structured Patches object.
    var program, vesselName;
    if (vessel.Patches !== null && vessel.Patches !== undefined) {
      program    = vessel.Patches.program.name;
      vesselName = vessel.Patches.vessel.name;
    } else {
      program    = null;
      vesselName = null;
    }

    return {
      db:       vessel.DB,
      name:     name,
      names:    names,
      soi:      soi,
      type:     type,
      start:    start,
      end:      end,
      program:  program,
      vessel:   vesselName,
      timeline: (vessel.Timeline !== null && vessel.Timeline !== undefined) ? vessel.Timeline : null,
      bodyRef:  bodyRef
    };
  }

  /**
   * fetchMenuData(ut, callback)
   *
   * Loads vessel and crew catalogs from DATABASE_JSON_ROOT, UT-seeks each
   * crew member's stats record, and delivers a structured result object to
   * loadMenuAJAX via _trackAndInvoke (Phase 3 convention — no delimited strings).
   *
   * Result shape: { vessels: vesselEntry[], crew: crewEntry[] }
   *
   * vesselEntry keys (all pre-computed at fetch time):
   *   db, name, names, soi, type, start, end, program, vessel, timeline, bodyRef
   *
   * crewEntry keys:
   *   fullName, status, rank, assignment, db, ut, deactivation, timeline
   *
   * This is the primary startup-critical endpoint: after it resolves,
   * loadMenuAJAX bootstraps the sidebar and triggers loadOpsDataAJAX for
   * all active entities.  Catalogs and kerbal index files are cached by
   * fetchJson so they are free on subsequent calls.
   *
   * @param {number}   ut        Current game UT in seconds.
   * @param {function} callback  loadMenuAJAX — receives (result).
   */
  function fetchMenuData(ut, callback) {
    var label = 'loadMenuData.asp?UT=' + ut;

    Promise.all([
      fetchJson(jsonCatalogFilePath('vessels')),
      fetchJson(jsonCatalogFilePath('crew'))
    ]).then(function (catalogs) {
      var vesselCatalog = catalogs[0];
      var crewCatalog   = catalogs[1];

      // For each crew member: load JSON index → seekToUT in stats array → load stats.
      var crewPromises = crewCatalog.map(function (crewItem) {
        return fetchJson(jsonIndexPath(crewItem.Kerbal)).then(function (index) {
          var statsUT = seekToUT(index.stats, ut);
          return fetchJson(jsonDbFilePath(crewItem.Kerbal, 'stats', statsUT))
            .then(function (statsRecord) {
              return { crewItem: crewItem, stats: statsRecord };
            });
        });
      });

      return Promise.all(crewPromises).then(function (crewResults) {
        return { vessels: vesselCatalog, crew: crewResults };
      });
    }).then(function (data) {

      // Build typed vessel entries — _buildMenuCraftRecord returns null for ref===-2.
      var vessels = [];
      data.vessels.forEach(function (vessel) {
        var entry = _buildMenuCraftRecord(vessel, ut);
        if (entry !== null) vessels.push(entry);
      });

      // Build typed crew entries.
      var crew = data.crew.map(function (result) {
        var c = result.crewItem;
        var s = result.stats;
        return {
          fullName:     c.FullName,
          status:       s.Status,
          rank:         s.Rank,
          assignment:   (s.Assignment !== null && s.Assignment !== undefined) ? s.Assignment : null,
          db:           c.Kerbal,
          ut:           s.UT,
          deactivation: c.Deactivation,
          timeline:     (c.Timeline !== null && c.Timeline !== undefined) ? c.Timeline : null
        };
      });

      _trackAndInvoke(label, callback, { vessels: vessels, crew: crew });
    })['catch'](function (err) {
      handleError(err, label, true);
    });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #7 — replaces loadEventData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchEventData(ut, callback)
   *
   * Scans all active, non-aircraft vessels for upcoming launch events and
   * planned maneuvers, then delivers a structured result to loadEventsAJAX
   * via _trackAndInvoke (Phase 3 convention — no delimited strings).
   *
   * Result shape: { launches: launchEntry[], maneuvers: maneuverEntry[] }
   *
   * launchEntry:   { UT, LaunchTime, db, Title, Desc }
   * maneuverEntry: { UT, ExecuteUT, db, Title, Desc }
   *
   * ASP logic preserved:
   *   - Iterate vessels catalog in catalog order (no sort — ASP's SortArray
   *     was defined but never called before output).
   *   - For each vessel, compute current SOI ref (last SOI entry UT <= ut).
   *     Default ref = -1 (vessel not yet active); skip if ref <= -1 or
   *     current type === 'aircraft'.
   *   - Load launch-times bulk file: one entry per row, LaunchTime null → 0.
   *   - Load index → seekToUT on flightplan array → load record: if
   *     ExecuteUT > ut, emit as a maneuver entry.
   *   - Maneuvers capped at the first two found (matching ASP two-slot output).
   *
   * The vessels catalog is already in _responseCache after fetchMenuData, so
   * that fetch is free.  Launch-times and index files are likewise cached,
   * making repeated calls (liftoff refresh, maneuver refresh) serve from memory.
   *
   * @param {number}   ut        Current game UT in seconds.
   * @param {function} callback  loadEventsAJAX — receives (result).
   */
  function fetchEventData(ut, callback) {
    var label = 'loadEventData.asp?UT=' + ut;

    fetchJson(jsonCatalogFilePath('vessels'))
      .then(function (vessels) {

        // Process all vessels concurrently, preserving catalog iteration order.
        var vesselPromises = vessels.map(function (vessel) {

          // Compute current SOI ref from pre-structured [{ut, ref}, ...] array.
          // Default -1 (vessel not yet active); differs from fetchMenuData
          // default 0 — intentional and correct here.
          var soi = vessel.SOI;
          var ref = -1;
          for (var i = 0; i < soi.length; i++) {
            if (soi[i].ut <= ut) ref = soi[i].ref;
            else break;
          }

          // Compute current type from pre-structured Type field (same pattern
          // as _buildMenuCraftRecord): plain string if single, array otherwise.
          var type;
          if (Array.isArray(vessel.Type)) {
            type = vessel.Type[0].type;
            for (var ti = 0; ti < vessel.Type.length; ti++) {
              if (vessel.Type[ti].ut === null || vessel.Type[ti].ut <= ut) type = vessel.Type[ti].type;
              else break;
            }
          } else {
            type = vessel.Type;
          }

          // Skip inactive (ref <= -1 covers -2) and aircraft.
          if (ref <= -1 || type === 'aircraft') {
            return Promise.resolve({ launches: [], flightplan: null });
          }

          // Compute current vessel name (same pattern as _buildMenuCraftRecord).
          var name;
          if (Array.isArray(vessel.Vessel)) {
            name = vessel.Vessel[0].name;
            for (var ni = 0; ni < vessel.Vessel.length; ni++) {
              if (vessel.Vessel[ni].ut === null || vessel.Vessel[ni].ut <= ut) name = vessel.Vessel[ni].name;
              else break;
            }
          } else {
            name = vessel.Vessel;
          }

          var db = vessel.DB;

          // Load launch times and index concurrently; errors treated as
          // "no data" so a missing file never aborts the whole response.
          var launchPromise = fetchJson(jsonBulkFilePath(db, 'launchtimes'))
            ['catch'](function () { return []; });

          var flightplanPromise = fetchJson(jsonIndexPath(db))
            .then(function (index) {
              if (!index.flightplan || !index.flightplan.length) return null;
              var fpUT = seekToUT(index.flightplan, ut);
              if (fpUT === null) return null;
              return fetchJson(jsonDbFilePath(db, 'flightplan', fpUT))
                ['catch'](function () { return null; });
            })
            ['catch'](function () { return null; });

          return Promise.all([launchPromise, flightplanPromise])
            .then(function (results) {
              var launchRows = results[0] || [];
              var fpRecord   = results[1];

              // Build typed launch entry objects; LaunchTime null → 0.
              var launchEntries = launchRows.map(function (row) {
                return {
                  UT:         row.UT,
                  LaunchTime: (row.LaunchTime !== null && row.LaunchTime !== undefined) ? row.LaunchTime : 0,
                  db:         db,
                  Title:      name,
                  Desc:       vessel.Desc
                };
              });

              // Flightplan entry: only if ExecuteUT is still in the future.
              var fpEntry = null;
              if (fpRecord && fpRecord.ExecuteUT > ut) {
                fpEntry = {
                  UT:        fpRecord.UT,
                  ExecuteUT: fpRecord.ExecuteUT,
                  db:        db,
                  Title:     name,
                  Desc:      fpRecord.Desc
                };
              }

              return { launches: launchEntries, flightplan: fpEntry };
            });
        });

        return Promise.all(vesselPromises);
      })
      .then(function (vesselResults) {

        // Collect in catalog-iteration order (no sort — matches ASP behavior).
        var allLaunches  = [];
        var allManeuvers = [];
        vesselResults.forEach(function (result) {
          result.launches.forEach(function (entry) { allLaunches.push(entry); });
          if (result.flightplan !== null) allManeuvers.push(result.flightplan);
        });

        _trackAndInvoke(label, callback, {
          launches:  allLaunches,
          maneuvers: allManeuvers.slice(0, 2)
        });
      })
      ['catch'](function (err) {
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #8 — replaces loadCrewData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchCrewData(db, ut, callback)
   *
   * Loads all data for a single crew member and delivers it to the existing
   * loadCrewAJAX callback in the same format that loadCrewData.asp produced.
   *
   * ASP logic replicated:
   *   Catalog section  — all fields from the Crew table for the given kerbal.
   *   Stats section    — UT-seek: largest UT <= current from [kerbal stats].
   *   Missions section — all mission rows with UT <= current, pipe-delimited;
   *                      "null" when empty or first row is in the future.
   *   Ribbons section  — same filter pattern as missions.
   *   Background section — UT-seek: largest UT <= current from [background].
   *   Future section   — next stats record, next mission, next ribbon, next
   *                      background (each "null" when none exists).
   *
   * The crew catalog is already cached in _responseCache after fetchMenuData
   * runs at startup, so that fetch is always a cache hit.  The kerbal index
   * is likewise cached after fetchMenuData pre-loaded it for the menu.
   *
   * Response format (separators):
   *   [catalog]*[stats]^[missions]^[ribbons]^[background]*
   *   [nextStats]^[nextMission]^[nextRibbon]^[nextBackground]
   *
   * @param {string}   db        Kerbal database ID (lowercase, e.g. "jeb").
   * @param {number}   ut        Current game UT in seconds.
   * @param {function} callback  Existing AJAX callback (loadCrewAJAX).
   */
  function fetchCrewData(db, ut, callback) {
    var label = 'loadCrewData.asp?db=' + db + '&ut=' + ut;

    // Catalog (cache hit after fetchMenuData), index, and bulk files in parallel.
    Promise.all([
      fetchJson(jsonCatalogFilePath('crew')),
      loadIndex(db),
      fetchJson(jsonBulkFilePath(db, 'missions'))['catch'](function () { return []; }),
      fetchJson(jsonBulkFilePath(db, 'ribbons'))['catch'](function () { return []; })
    ]).then(function (results) {
      var crewCatalog = results[0];
      var index       = results[1];
      var allMissions = results[2];
      var allRibbons  = results[3];

      // Locate this kerbal's catalog entry (compare against Kerbal field, not DB).
      var crewEntry = crewCatalog.find(function (c) { return c.Kerbal === db; });

      // UT-seek for current and next stats / background.
      var statsUT     = seekToUT(index.stats,      ut);
      var bgUT        = seekToUT(index.background, ut);
      var nextStatsUT = getNextUT(index.stats,      ut);
      var nextBgUT    = getNextUT(index.background, ut);

      // Fetch current + next stats and background files concurrently.
      return Promise.all([
        fetchJson(jsonDbFilePath(db, 'stats',      statsUT)),
        fetchJson(jsonDbFilePath(db, 'background', bgUT)),
        nextStatsUT !== null
          ? fetchJson(jsonDbFilePath(db, 'stats', nextStatsUT))['catch'](function () { return null; })
          : Promise.resolve(null),
        nextBgUT !== null
          ? fetchJson(jsonDbFilePath(db, 'background', nextBgUT))['catch'](function () { return null; })
          : Promise.resolve(null)
      ]).then(function (fetched) {
        return {
          crewEntry:   crewEntry,
          stats:       fetched[0],
          background:  fetched[1],
          nextStats:   fetched[2],
          nextBg:      fetched[3],
          allMissions: allMissions,
          allRibbons:  allRibbons
        };
      });
    }).then(function (d) {

      // Missions up to current UT, newest-first for loadCrewAJAX.
      var currentMissions = d.allMissions.filter(function (m) { return m.UT <= ut; });
      currentMissions.reverse();

      // Ribbons up to current UT (ascending order — matches display logic).
      var currentRibbons = d.allRibbons.filter(function (r) { return r.UT <= ut; });

      // Normalize integer fields that may be strings in older DB exports.
      _normalizeStatsRecord(d.stats);
      _normalizeStatsRecord(d.nextStats);

      // Next future records (first item past current UT).
      var nextMission = d.allMissions.find(function (m) { return m.UT > ut; }) || null;
      var nextRibbon  = d.allRibbons.find(function (r) { return r.UT > ut; }) || null;

      _trackAndInvoke(label, callback, {
        catalog:    d.crewEntry,
        stats:      d.stats,
        background: d.background,
        missions:   currentMissions,
        ribbons:    currentRibbons,
        next: {
          stats:      d.nextStats || null,
          mission:    nextMission,
          ribbon:     nextRibbon,
          background: d.nextBg || null
        }
      });
    })['catch'](function (err) {
      handleError(err, label, true);
    });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #9 — replaces loadVesselOrbitData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchVesselOrbitData(db, ut, callback, data)
   *
   * UT-seeks the flightdata and flightplan tables for a vessel and delivers
   * a structured result to addOrbitAJAX or loadVesselOrbitAJAX via
   * _trackAndInvoke (Phase 3 convention — no delimited strings).
   *
   * Result shape: { db, flightData: obj|null, flightPlan: obj|null }
   * Keys are normalized (spaces stripped) so field names like "Orbital Period"
   * become "OrbitalPeriod" for direct property access.
   *
   * Cache behaviour: fetchJson() caches by URL, so if fetchVesselData (#10)
   * already loaded the same index and flightdata file, this call is a cache
   * hit with zero network round-trips.
   *
   * @param {string}   db        Vessel DB name (e.g. "kerbin-II").
   * @param {number}   ut        Current game UT in seconds.
   * @param {function} callback  addOrbitAJAX or loadVesselOrbitAJAX.
   * @param {*}        [data]    Optional pass-through value (e.g. currObj for loadVesselOrbitAJAX).
   */
  function fetchVesselOrbitData(db, ut, callback, data) {
    var label = 'loadVesselOrbitData.asp?db=' + db + '&ut=' + ut;

    fetchJson(jsonIndexPath(db))
      ['catch'](function () { return {}; })   // missing index → all-null response
      .then(function (index) {

        // UT-seek each table; null when the table has no entries in the index.
        var fdUT = (index.flightdata && index.flightdata.length)
          ? seekToUT(index.flightdata, ut)
          : null;
        var fpUT = (index.flightplan && index.flightplan.length)
          ? seekToUT(index.flightplan, ut)
          : null;

        var fdPromise = fdUT !== null
          ? fetchJson(jsonDbFilePath(db, 'flightdata', fdUT))['catch'](function () { return null; })
          : Promise.resolve(null);

        var fpPromise = fpUT !== null
          ? fetchJson(jsonDbFilePath(db, 'flightplan', fpUT))['catch'](function () { return null; })
          : Promise.resolve(null);

        return Promise.all([fdPromise, fpPromise]);
      })
      .then(function (results) {
        _trackAndInvoke(label, callback, {
          db:         db,
          flightData: _normalizeKeys(results[0]),
          flightPlan: _normalizeKeys(results[1])
        }, data);
      })
      ['catch'](function (err) {
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #10 — replaces loadVesselData.asp
  // ---------------------------------------------------------------------------

  /**
   * _boolStr(val)
   *
   * Private helper: converts a JS boolean (or boolean-like value) to a
   * lowercase string ("true" / "false").
   */
  function _boolStr(val) {
    return val ? 'true' : 'false';
  }

  /**
   * fetchVesselData(db, ut, pastUT, callback, data)
   *
   * The most complex endpoint: loads all data tables for a single vessel and
   * delivers them to the existing loadVesselAJAX callback in the same format
   * that loadVesselData.asp produced.
   *
   * ASP logic replicated (in output order):
   *
   *   Header: "<db>Typ3"
   *
   *   Segment 0 — Catalog: all fields from the Crafts table for this vessel.
   *     Separator: "*"
   *
   *   Segment 1 — Ascent data range:
   *     "<firstUT>~<lastUT>"  when ascent data exists
   *     "false"               when the ascent data table is empty
   *     Separator: "*"
   *
   *   Segment 2 — Current record tables (caret-delimited):
   *     [craftdata]^[resources`NotNull~T/F]^[manifest]^[comms`NotNull~T/F]^[flightdata]^[ports]
   *     Each table: objToRs(record) or "null" when BOF (no record for this UT).
   *     Resources and comms uniquely add "`NotNull~true/false" after objToRs()
   *     (mirroring ASP's append-after-stripped-backtick pattern; see FC-3).
   *     Field names have spaces stripped (e.g. "Avg Velocity" → "AvgVelocity"),
   *     which objToRs() already does via replace(/ /g, '').
   *     Separator: "*"
   *
   *   Segment 3 — Event history (all craftdata records):
   *     "UT~CraftDescTitle|UT~CraftDescTitle|…"  (no trailing "|")
   *     Separator: "*"
   *
   *   Segment 4 — Launch times (all rows):
   *     "UT~LaunchTime|…"  or  "null"  when empty
   *     Separator: "*"
   *
   *   Segment 5 — Orbital period history (all flightdata records, up to last):
   *     "UT~OrbitalPeriod|…"  or  "null"  when empty
   *     (The last segment has no trailing "*" — stripped by ASP's final left())
   *
   * pastUT parameter: originally intended for history paging but the ASP code
   * comments it out as non-functional ("can't figure out what this was").
   * The fetch* implementation ignores it entirely (matches ASP behaviour).
   *
   * History section uses Option A (see FC-1 in plan.md): all craftdata and
   * flightdata files are fetched in parallel via Promise.all, then sorted by UT.
   * All results are cached by fetchJson so second loads within the session
   * are served from memory.
   *
   * @param {string}   db        Vessel DB name (e.g. "ascensionmk2-2").
   * @param {number}   ut        Current game UT in seconds.
   * @param {number}   pastUT    Ignored (non-functional in ASP; kept for signature parity).
   * @param {function} callback  Existing AJAX callback (loadVesselAJAX).
   * @param {*}        [data]    Optional pass-through value.
   */
  function fetchVesselData(db, ut, pastUT, callback, data) {
    var label = 'loadVesselData.asp?db=' + db + '&ut=' + ut;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);

    // Step 1: load catalog entry (cache hit after fetchMenuData) + vessel index.
    Promise.all([
      fetchJson(catalogFilePath('vessels')),
      loadIndex(db)['catch'](function () { return {}; }),
      fetchJson(bulkFilePath(db, 'ascentdata'))['catch'](function () { return []; }),
      fetchJson(bulkFilePath(db, 'launchtimes'))['catch'](function () { return []; })
    ]).then(function (step1) {
      var vesselCatalog = step1[0];
      var index         = step1[1];
      var ascentRows    = step1[2];
      var launchRows    = step1[3];

      // Locate this vessel's catalog entry.
      var catalogEntry = null;
      for (var vi = 0; vi < vesselCatalog.length; vi++) {
        if (vesselCatalog[vi].DB === db) { catalogEntry = vesselCatalog[vi]; break; }
      }

      // UT-seek for each of the 6 current-record tables.
      var cdUT  = (index.craftdata  && index.craftdata.length)  ? seekToUT(index.craftdata,  ut) : null;
      var resUT = (index.resources  && index.resources.length)  ? seekToUT(index.resources,  ut) : null;
      var mnUT  = (index.manifest   && index.manifest.length)   ? seekToUT(index.manifest,   ut) : null;
      var cmUT  = (index.comms      && index.comms.length)      ? seekToUT(index.comms,      ut) : null;
      var fdUT  = (index.flightdata && index.flightdata.length)  ? seekToUT(index.flightdata, ut) : null;
      var ptUT  = (index.ports      && index.ports.length)      ? seekToUT(index.ports,      ut) : null;
      // Future-guard: seekToUT returns utArray[0] when all elements > targetUT, but
      // ASP outputs "null" when its cursor reaches BOF before finding any UT <= targetUT.
      if (cdUT  !== null && cdUT  > ut) cdUT  = null;
      if (resUT !== null && resUT > ut) resUT = null;
      if (mnUT  !== null && mnUT  > ut) mnUT  = null;
      if (cmUT  !== null && cmUT  > ut) cmUT  = null;
      if (fdUT  !== null && fdUT  > ut) fdUT  = null;
      if (ptUT  !== null && ptUT  > ut) ptUT  = null;

      // Fetch all current-record files + all history files in parallel (Option A).
      // History: every craftdata file (for event list) + every flightdata file (for orbit history).
      var allCraftdataUTs  = (index.craftdata  || []);
      var allFlightdataUTs = (index.flightdata || []);

      var currentFetches = [
        cdUT  !== null ? fetchJson(dbFilePath(db, 'craftdata',  cdUT))['catch'](function () { return null; }) : Promise.resolve(null),
        resUT !== null ? fetchJson(dbFilePath(db, 'resources',  resUT))['catch'](function () { return null; }) : Promise.resolve(null),
        mnUT  !== null ? fetchJson(dbFilePath(db, 'manifest',   mnUT))['catch'](function () { return null; }) : Promise.resolve(null),
        cmUT  !== null ? fetchJson(dbFilePath(db, 'comms',      cmUT))['catch'](function () { return null; }) : Promise.resolve(null),
        fdUT  !== null ? fetchJson(dbFilePath(db, 'flightdata', fdUT))['catch'](function () { return null; }) : Promise.resolve(null),
        ptUT  !== null ? fetchJson(dbFilePath(db, 'ports',      ptUT))['catch'](function () { return null; }) : Promise.resolve(null)
      ];

      // History fetches: all craftdata and flightdata files.
      var historyFetches = allCraftdataUTs.map(function (hUT) {
        return fetchJson(dbFilePath(db, 'craftdata', hUT))['catch'](function () { return null; });
      });
      var orbitHistFetches = allFlightdataUTs.map(function (hUT) {
        return fetchJson(dbFilePath(db, 'flightdata', hUT))['catch'](function () { return null; });
      });

      return Promise.all(currentFetches.concat(historyFetches).concat(orbitHistFetches))
        .then(function (fetched) {
          var nHistory  = allCraftdataUTs.length;
          var nOrbitHis = allFlightdataUTs.length;

          return {
            catalogEntry:   catalogEntry,
            ascentRows:     ascentRows,
            launchRows:     launchRows,
            craftRecord:    fetched[0],
            resRecord:      fetched[1],
            mnRecord:       fetched[2],
            cmRecord:       fetched[3],
            fdRecord:       fetched[4],
            ptRecord:       fetched[5],
            allCraftdata:   fetched.slice(6, 6 + nHistory),
            allFlightdata:  fetched.slice(6 + nHistory, 6 + nHistory + nOrbitHis)
          };
        });
    }).then(function (d) {

      // --- Segment 0: catalog ---
      var catalogRs = objToRs(d.catalogEntry);

      // --- Segment 1: ascent data range ---
      var ascentSeg;
      if (d.ascentRows && d.ascentRows.length > 0) {
        ascentSeg = d.ascentRows[0].UT + '~' + d.ascentRows[d.ascentRows.length - 1].UT;
      } else {
        ascentSeg = 'false';
      }

      // --- Segment 2: current record tables (caret-delimited) ---

      // craftdata
      var cdRs = d.craftRecord ? objToRs(d.craftRecord) : 'null';

      // resources: append "`NotNull~True/False" — see FC-3 in plan.md.
      var resRs;
      if (d.resRecord) {
        var resNotNull = false;
        var resKeys = Object.keys(d.resRecord);
        for (var ri = 0; ri < resKeys.length; ri++) {
          var rk = resKeys[ri];
          if (rk !== 'UT' && d.resRecord[rk] !== null && d.resRecord[rk] !== undefined && d.resRecord[rk] !== '') {
            resNotNull = true; break;
          }
        }
        resRs = objToRs(d.resRecord) + '`NotNull~' + _boolStr(resNotNull);
      } else {
        resRs = 'null';
      }

      // manifest (crew) — plain objToRs, no NotNull
      var mnRs = d.mnRecord ? objToRs(d.mnRecord) : 'null';

      // comms: append "`NotNull~True/False".
      // ASP condition: field name !== "UT" OR field name !== "Connection" AND value !== ""
      // (note: the ASP uses OR which is always true for any field, effectively: any non-empty value → NotNull)
      // Functionally: if Comms field (the antenna string) is non-empty → True.
      var cmRs;
      if (d.cmRecord) {
        var cmNotNull = false;
        var cmKeys = Object.keys(d.cmRecord);
        for (var ci = 0; ci < cmKeys.length; ci++) {
          var ck = cmKeys[ci];
          if (d.cmRecord[ck] !== null && d.cmRecord[ck] !== undefined && d.cmRecord[ck] !== '') {
            cmNotNull = true; break;
          }
        }
        cmRs = objToRs(d.cmRecord) + '`NotNull~' + _boolStr(cmNotNull);
      } else {
        cmRs = 'null';
      }

      // flightdata (orbital data) — plain objToRs, no NotNull
      var fdRs = d.fdRecord ? objToRs(d.fdRecord) : 'null';

      // ports — plain objToRs, no NotNull
      var ptRs = d.ptRecord ? objToRs(d.ptRecord) : 'null';

      var tablesSeg = cdRs + '^' + resRs + '^' + mnRs + '^' + cmRs + '^' + fdRs + '^' + ptRs;

      // --- Segment 3: event history (all craftdata records, sorted by UT) ---
      // Filter nulls (failed fetches), sort by UT, then emit "UT~CraftDescTitle".
      var historyItems = d.allCraftdata
        .filter(function (r) { return r !== null; })
        .sort(function (a, b) { return a.UT - b.UT; });
      var historySeg = historyItems
        .map(function (r) { return r.UT + '~' + (r.CraftDescTitle || ''); })
        .join('|');

      // --- Segment 4: launch times (all rows) ---
      var launchSeg;
      if (d.launchRows && d.launchRows.length > 0) {
        launchSeg = d.launchRows
          .map(function (r) { return r.UT + '~' + (r.LaunchTime !== null && r.LaunchTime !== undefined ? r.LaunchTime : ''); })
          .join('|');
      } else {
        launchSeg = 'null';
      }

      // --- Segment 5: orbital period history (all flightdata records, sorted by UT) ---
      // "Orbital Period" field → stored as "Orbital Period" in JSON, stripped to "OrbitalPeriod"
      // by objToRs but here we only emit UT~Period pairs (not a full RS), so read directly.
      var orbitHistItems = d.allFlightdata
        .filter(function (r) { return r !== null; })
        .sort(function (a, b) { return a.UT - b.UT; });

      var orbitHistSeg;
      if (orbitHistItems.length > 0) {
        // Include ALL records — null Orbital Period emits as empty string ("UT~"),
        // matching VBScript's null-to-empty coercion in the ASP output (e.g. re-entry records).
        orbitHistSeg = orbitHistItems
          .map(function (r) {
            var period = (r['Orbital Period'] !== null && r['Orbital Period'] !== undefined)
              ? r['Orbital Period'] : '';
            return r.UT + '~' + period;
          })
          .join('|');
      } else {
        orbitHistSeg = 'null';
      }

      // Final assembly:
      // "<db>Typ3" + seg0 + "*" + seg1 + "*" + seg2 + "*" + seg3 + "*" + seg4 + "*" + seg5
      // (no trailing "*" — ASP's left(output, len(output)-1) strips it)
      var rs = db + 'Typ3' +
               catalogRs    + '*' +
               ascentSeg    + '*' +
               tablesSeg    + '*' +
               historySeg   + '*' +
               launchSeg    + '*' +
               orbitHistSeg;

      _parity(label, rs);
      dbResponse({ responseText: rs }, label, callback, data);
    })['catch'](function (err) {
      var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
      if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
      handleError(err, label, true);
    });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #11 — replaces loadOpsData.asp
  // ---------------------------------------------------------------------------

  /**
   * fetchOpsData(db, ut, type, pastUT, callback, data)
   *
   * Real-time update endpoint: loads data for one vessel or crew member and
   * delivers it to the existing loadOpsDataAJAX callback in the same format
   * that loadOpsData.asp produced.
   *
   * ASP logic replicated:
   *   type="vessel" — <db>Typ3vessel + catalog * ascent data * current 6
   *     tables (craftdata/resources/manifest/comms/flightdata/ports, with
   *     PastEvent~false on craftdata and NotNull on resources + comms) *
   *     future 6 tables (same order, NotNull for resources + comms) *
   *     event history (UT~Title|…) * launch times * orbit period history.
   *   type="crew"   — <db>Typ3crew + catalog * stats^missions^ribbons^
   *     background * next stats^next mission^next ribbon^next background.
   *     Identical to loadCrewData.asp output with the Typ3crew prefix.
   *
   * pastUT is always NaN at all call sites; the pastUT seek path is not
   * implemented (PastEvent is always "false" in practice).
   *
   * Cache behaviour: index files, record files, and bulk files are shared
   * with fetchVesselData / fetchCrewData via _indexCache / _responseCache,
   * so calls after the initial load are served entirely from cache.
   *
   * @param {string}   db       Entity DB name (e.g. "kerbin-II" or "jeb").
   * @param {number}   ut       Current game UT in seconds.
   * @param {string}   type     "vessel" or "crew".
   * @param {number}   pastUT   Always NaN at call sites; accepted but unused.
   * @param {function} callback Existing AJAX callback (loadOpsDataAJAX).
   * @param {*}        [data]   Optional pass-through value.
   */
  function fetchOpsData(db, ut, type, pastUT, callback, data) {
    var label = 'loadOpsData.asp?db=' + db + '&UT=' + ut + '&type=' + type +
                '&pastUT=' + (isNaN(pastUT) ? 'NaN' : pastUT);
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);

    if (type === 'crew') {
      _fetchOpsCrewData(db, ut, label, callback, data);
    } else {
      _fetchOpsVesselData(db, ut, label, callback, data);
    }
  }

  /**
   * _fetchOpsCrewData — private: assembles the crew-path response for fetchOpsData.
   *
   * Response format (mirrors loadOpsData.asp crew branch and loadCrewData.asp):
   *   <db>Typ3crew<catalog>*<stats>^<missions>^<ribbons>^<background>*
   *   <nextStats>^<nextMission>^<nextRibbon>^<nextBackground>
   */
  function _fetchOpsCrewData(db, ut, label, callback, data) {
    Promise.all([
      fetchJson(catalogFilePath('crew')),
      loadIndex(db),
      fetchJson(bulkFilePath(db, 'missions'))['catch'](function () { return []; }),
      fetchJson(bulkFilePath(db, 'ribbons'))['catch'](function () { return []; })
    ]).then(function (results) {
      var crewCatalog = results[0];
      var index       = results[1];
      var allMissions = results[2];
      var allRibbons  = results[3];

      var crewEntry = crewCatalog.find(function (c) { return c.Kerbal === db; });

      var statsUT    = seekToUT(index.stats,      ut);
      var bgUT       = seekToUT(index.background, ut);
      var nextStatsUT = getNextUT(index.stats,      ut);
      var nextBgUT    = getNextUT(index.background, ut);

      return Promise.all([
        fetchJson(dbFilePath(db, 'stats',      statsUT)),
        fetchJson(dbFilePath(db, 'background', bgUT)),
        nextStatsUT !== null
          ? fetchJson(dbFilePath(db, 'stats', nextStatsUT))['catch'](function () { return null; })
          : Promise.resolve(null),
        nextBgUT !== null
          ? fetchJson(dbFilePath(db, 'background', nextBgUT))['catch'](function () { return null; })
          : Promise.resolve(null)
      ]).then(function (fetched) {
        return {
          crewEntry:   crewEntry,
          stats:       fetched[0],
          background:  fetched[1],
          nextStats:   fetched[2],
          nextBg:      fetched[3],
          allMissions: allMissions,
          allRibbons:  allRibbons
        };
      });
    }).then(function (d) {
      var catalogRs = objToRs(d.crewEntry);
      var statsRs   = objToRs(d.stats);

      var currentMissions = d.allMissions.filter(function (m) { return m.UT <= ut; });
      var missionsRs = currentMissions.length > 0
        ? currentMissions.map(objToRs).join('|')
        : 'null';

      var currentRibbons = d.allRibbons.filter(function (r) { return r.UT <= ut; });
      var ribbonsRs = currentRibbons.length > 0
        ? currentRibbons.map(objToRs).join('|')
        : 'null';

      var bgRs        = objToRs(d.background);
      var nextStatsRs = d.nextStats ? objToRs(d.nextStats) : 'null';
      var nextMission   = d.allMissions.find(function (m) { return m.UT > ut; });
      var nextMissionRs = nextMission ? objToRs(nextMission) : 'null';
      var nextRibbon    = d.allRibbons.find(function (r) { return r.UT > ut; });
      var nextRibbonRs  = nextRibbon ? objToRs(nextRibbon) : 'null';
      var nextBgRs      = d.nextBg ? objToRs(d.nextBg) : 'null';

      var rs = db + 'Typ3crew' +
               catalogRs + '*' +
               statsRs + '^' + missionsRs + '^' + ribbonsRs + '^' + bgRs +
               '*' +
               nextStatsRs + '^' + nextMissionRs + '^' + nextRibbonRs + '^' + nextBgRs;

      _parity(label, rs);
      dbResponse({ responseText: rs }, label, callback, data);
    })['catch'](function (err) {
      var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
      if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
      handleError(err, label, true);
    });
  }

  /**
   * _fetchOpsVesselData — private: assembles the vessel-path response for fetchOpsData.
   *
   * Response format (mirrors loadOpsData.asp vessel branch):
   *   <db>Typ3vessel<catalog>*<ascentRows|null>*<currentSeg>*<futureSeg>*
   *   <historySeg>*<launchSeg>*<orbitHistSeg>
   *
   * currentSeg  = craftdataRS`PastEvent~false^resRS`NotNull~X^manifestRS^
   *               commsRS`NotNull~X^flightdataRS^portsRS
   * futureSeg   = same 6 slots, no PastEvent, NotNull uses AND logic (field≠'UT').
   *
   * NotNull — current resources:  field !== 'UT' AND non-empty (AND logic)
   * NotNull — current comms:      any non-empty field value (effective OR logic per ASP)
   * NotNull — future resources:   field !== 'UT' AND non-empty
   * NotNull — future comms:       field !== 'UT' AND non-empty
   */
  function _fetchOpsVesselData(db, ut, label, callback, data) {
    Promise.all([
      fetchJson(catalogFilePath('vessels')),
      loadIndex(db)['catch'](function () { return {}; }),
      fetchJson(bulkFilePath(db, 'ascentdata'))['catch'](function () { return []; }),
      fetchJson(bulkFilePath(db, 'launchtimes'))['catch'](function () { return []; })
    ]).then(function (step1) {
      var vesselCatalog = step1[0];
      var index         = step1[1];
      var ascentRows    = step1[2];
      var launchRows    = step1[3];

      var catalogEntry = null;
      for (var vi = 0; vi < vesselCatalog.length; vi++) {
        if (vesselCatalog[vi].DB === db) { catalogEntry = vesselCatalog[vi]; break; }
      }

      // UT-seek for current records.
      var cdUT  = (index.craftdata  && index.craftdata.length)  ? seekToUT(index.craftdata,  ut) : null;
      var resUT = (index.resources  && index.resources.length)  ? seekToUT(index.resources,  ut) : null;
      var mnUT  = (index.manifest   && index.manifest.length)   ? seekToUT(index.manifest,   ut) : null;
      var cmUT  = (index.comms      && index.comms.length)      ? seekToUT(index.comms,      ut) : null;
      var fdUT  = (index.flightdata && index.flightdata.length) ? seekToUT(index.flightdata, ut) : null;
      var ptUT  = (index.ports      && index.ports.length)      ? seekToUT(index.ports,      ut) : null;
      // Future-guard: seekToUT returns utArray[0] when all UTs > targetUT; null those out.
      if (cdUT  !== null && cdUT  > ut) cdUT  = null;
      if (resUT !== null && resUT > ut) resUT = null;
      if (mnUT  !== null && mnUT  > ut) mnUT  = null;
      if (cmUT  !== null && cmUT  > ut) cmUT  = null;
      if (fdUT  !== null && fdUT  > ut) fdUT  = null;
      if (ptUT  !== null && ptUT  > ut) ptUT  = null;

      // getNextUT for future records.
      var futCdUT  = (index.craftdata  && index.craftdata.length)  ? getNextUT(index.craftdata,  ut) : null;
      var futResUT = (index.resources  && index.resources.length)  ? getNextUT(index.resources,  ut) : null;
      var futMnUT  = (index.manifest   && index.manifest.length)   ? getNextUT(index.manifest,   ut) : null;
      var futCmUT  = (index.comms      && index.comms.length)      ? getNextUT(index.comms,      ut) : null;
      var futFdUT  = (index.flightdata && index.flightdata.length) ? getNextUT(index.flightdata, ut) : null;
      var futPtUT  = (index.ports      && index.ports.length)      ? getNextUT(index.ports,      ut) : null;

      var allCraftdataUTs  = (index.craftdata  || []);
      var allFlightdataUTs = (index.flightdata || []);

      var fetches = [
        cdUT    !== null ? fetchJson(dbFilePath(db, 'craftdata',  cdUT))['catch'](function () { return null; })  : Promise.resolve(null),
        resUT   !== null ? fetchJson(dbFilePath(db, 'resources',  resUT))['catch'](function () { return null; }) : Promise.resolve(null),
        mnUT    !== null ? fetchJson(dbFilePath(db, 'manifest',   mnUT))['catch'](function () { return null; })  : Promise.resolve(null),
        cmUT    !== null ? fetchJson(dbFilePath(db, 'comms',      cmUT))['catch'](function () { return null; })  : Promise.resolve(null),
        fdUT    !== null ? fetchJson(dbFilePath(db, 'flightdata', fdUT))['catch'](function () { return null; })  : Promise.resolve(null),
        ptUT    !== null ? fetchJson(dbFilePath(db, 'ports',      ptUT))['catch'](function () { return null; })  : Promise.resolve(null),
        futCdUT  !== null ? fetchJson(dbFilePath(db, 'craftdata',  futCdUT))['catch'](function () { return null; })  : Promise.resolve(null),
        futResUT !== null ? fetchJson(dbFilePath(db, 'resources',  futResUT))['catch'](function () { return null; }) : Promise.resolve(null),
        futMnUT  !== null ? fetchJson(dbFilePath(db, 'manifest',   futMnUT))['catch'](function () { return null; })  : Promise.resolve(null),
        futCmUT  !== null ? fetchJson(dbFilePath(db, 'comms',      futCmUT))['catch'](function () { return null; })  : Promise.resolve(null),
        futFdUT  !== null ? fetchJson(dbFilePath(db, 'flightdata', futFdUT))['catch'](function () { return null; })  : Promise.resolve(null),
        futPtUT  !== null ? fetchJson(dbFilePath(db, 'ports',      futPtUT))['catch'](function () { return null; })  : Promise.resolve(null)
      ];

      var historyFetches = allCraftdataUTs.map(function (hUT) {
        return fetchJson(dbFilePath(db, 'craftdata', hUT))['catch'](function () { return null; });
      });
      var orbitHistFetches = allFlightdataUTs.map(function (hUT) {
        return fetchJson(dbFilePath(db, 'flightdata', hUT))['catch'](function () { return null; });
      });

      return Promise.all(fetches.concat(historyFetches).concat(orbitHistFetches))
        .then(function (fetched) {
          var nHistory  = allCraftdataUTs.length;
          var nOrbitHis = allFlightdataUTs.length;
          return {
            catalogEntry: catalogEntry,
            ascentRows:   ascentRows,
            launchRows:   launchRows,
            craftRecord:  fetched[0],
            resRecord:    fetched[1],
            mnRecord:     fetched[2],
            cmRecord:     fetched[3],
            fdRecord:     fetched[4],
            ptRecord:     fetched[5],
            futCdRecord:  fetched[6],
            futResRecord: fetched[7],
            futMnRecord:  fetched[8],
            futCmRecord:  fetched[9],
            futFdRecord:  fetched[10],
            futPtRecord:  fetched[11],
            allCraftdata:  fetched.slice(12, 12 + nHistory),
            allFlightdata: fetched.slice(12 + nHistory, 12 + nHistory + nOrbitHis)
          };
        });
    }).then(function (d) {

      // --- Catalog ---
      var catalogRs = objToRs(d.catalogEntry);

      // --- Ascent data: full pipe-delimited record rows (or "null") ---
      var ascentSeg = (d.ascentRows && d.ascentRows.length > 0)
        ? d.ascentRows.map(objToRs).join('|')
        : 'null';

      // --- Current craftdata + PastEvent~false (pastUT is always NaN at call sites) ---
      var cdRs = d.craftRecord
        ? objToRs(d.craftRecord) + '`PastEvent~false'
        : 'null';

      // --- Current resources + NotNull (AND logic: field !== 'UT' AND non-empty) ---
      var resRs;
      if (d.resRecord) {
        var resNotNull = false;
        var resKeys = Object.keys(d.resRecord);
        for (var ri = 0; ri < resKeys.length; ri++) {
          var rk = resKeys[ri];
          if (rk !== 'UT' && d.resRecord[rk] !== null && d.resRecord[rk] !== undefined && d.resRecord[rk] !== '') {
            resNotNull = true; break;
          }
        }
        resRs = objToRs(d.resRecord) + '`NotNull~' + _boolStr(resNotNull);
      } else {
        resRs = 'null';
      }

      // --- Current manifest ---
      var mnRs = d.mnRecord ? objToRs(d.mnRecord) : 'null';

      // --- Current comms + NotNull (any non-empty value → True, per ASP OR logic) ---
      var cmRs;
      if (d.cmRecord) {
        var cmNotNull = false;
        var cmKeys = Object.keys(d.cmRecord);
        for (var ci = 0; ci < cmKeys.length; ci++) {
          if (d.cmRecord[cmKeys[ci]] !== null && d.cmRecord[cmKeys[ci]] !== undefined && d.cmRecord[cmKeys[ci]] !== '') {
            cmNotNull = true; break;
          }
        }
        cmRs = objToRs(d.cmRecord) + '`NotNull~' + _boolStr(cmNotNull);
      } else {
        cmRs = 'null';
      }

      // --- Current flightdata and ports ---
      var fdRs = d.fdRecord ? objToRs(d.fdRecord) : 'null';
      var ptRs = d.ptRecord ? objToRs(d.ptRecord) : 'null';

      var currentSeg = cdRs + '^' + resRs + '^' + mnRs + '^' + cmRs + '^' + fdRs + '^' + ptRs;

      // --- Future craftdata (no PastEvent) ---
      var futCdRs = d.futCdRecord ? objToRs(d.futCdRecord) : 'null';

      // --- Future resources + NotNull (AND logic: field !== 'UT' AND non-empty) ---
      var futResRs;
      if (d.futResRecord) {
        var futResNotNull = false;
        var futResKeys = Object.keys(d.futResRecord);
        for (var fri = 0; fri < futResKeys.length; fri++) {
          var frk = futResKeys[fri];
          if (frk !== 'UT' && d.futResRecord[frk] !== null && d.futResRecord[frk] !== undefined && d.futResRecord[frk] !== '') {
            futResNotNull = true; break;
          }
        }
        futResRs = objToRs(d.futResRecord) + '`NotNull~' + _boolStr(futResNotNull);
      } else {
        futResRs = 'null';
      }

      // --- Future manifest ---
      var futMnRs = d.futMnRecord ? objToRs(d.futMnRecord) : 'null';

      // --- Future comms + NotNull (AND logic: field !== 'UT' AND non-empty, per ASP future branch) ---
      var futCmRs;
      if (d.futCmRecord) {
        var futCmNotNull = false;
        var futCmKeys = Object.keys(d.futCmRecord);
        for (var fci = 0; fci < futCmKeys.length; fci++) {
          var fck = futCmKeys[fci];
          if (fck !== 'UT' && d.futCmRecord[fck] !== null && d.futCmRecord[fck] !== undefined && d.futCmRecord[fck] !== '') {
            futCmNotNull = true; break;
          }
        }
        futCmRs = objToRs(d.futCmRecord) + '`NotNull~' + _boolStr(futCmNotNull);
      } else {
        futCmRs = 'null';
      }

      // --- Future flightdata and ports ---
      var futFdRs = d.futFdRecord ? objToRs(d.futFdRecord) : 'null';
      var futPtRs = d.futPtRecord ? objToRs(d.futPtRecord) : 'null';

      var futureSeg = futCdRs + '^' + futResRs + '^' + futMnRs + '^' + futCmRs + '^' + futFdRs + '^' + futPtRs;

      // --- Event history: all craftdata records sorted by UT (UT~CraftDescTitle|…) ---
      var historyItems = d.allCraftdata
        .filter(function (r) { return r !== null; })
        .sort(function (a, b) { return a.UT - b.UT; });
      var historySeg = historyItems
        .map(function (r) { return r.UT + '~' + (r.CraftDescTitle || ''); })
        .join('|');

      // --- Launch times ---
      var launchSeg;
      if (d.launchRows && d.launchRows.length > 0) {
        launchSeg = d.launchRows
          .map(function (r) { return r.UT + '~' + (r.LaunchTime !== null && r.LaunchTime !== undefined ? r.LaunchTime : ''); })
          .join('|');
      } else {
        launchSeg = 'null';
      }

      // --- Orbital period history: all flightdata records sorted by UT (UT~Period|…) ---
      var orbitHistItems = d.allFlightdata
        .filter(function (r) { return r !== null; })
        .sort(function (a, b) { return a.UT - b.UT; });
      var orbitHistSeg;
      if (orbitHistItems.length > 0) {
        orbitHistSeg = orbitHistItems
          .map(function (r) {
            var period = (r['Orbital Period'] !== null && r['Orbital Period'] !== undefined)
              ? r['Orbital Period'] : '';
            return r.UT + '~' + period;
          })
          .join('|');
      } else {
        orbitHistSeg = 'null';
      }

      var rs = db + 'Typ3vessel' +
               catalogRs  + '*' +
               ascentSeg  + '*' +
               currentSeg + '*' +
               futureSeg  + '*' +
               historySeg + '*' +
               launchSeg  + '*' +
               orbitHistSeg;

      _parity(label, rs);
      dbResponse({ responseText: rs }, label, callback, data);
    })['catch'](function (err) {
      var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
      if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
      handleError(err, label, true);
    });
  }

  // ===========================================================================
  // EXPORTS
  // ===========================================================================

  return {
    // Core data utilities
    seekToUT:        seekToUT,
    getNextUT:       getNextUT,
    fetchJson:       fetchJson,
    objToRs:         objToRs,
    invokeCallback:  invokeCallback,
    _trackAndInvoke: _trackAndInvoke,
    // Index management
    loadIndex:       loadIndex,
    // Path helpers (legacy — DATABASE_ROOT)
    indexPath:       indexPath,
    dbFilePath:      dbFilePath,
    bulkFilePath:    bulkFilePath,
    catalogFilePath: catalogFilePath,
    flightFilePath:  flightFilePath,
    // Path helpers (JSON — DATABASE_JSON_ROOT)
    jsonIndexPath:       jsonIndexPath,
    jsonDbFilePath:      jsonDbFilePath,
    jsonBulkFilePath:    jsonBulkFilePath,
    jsonCatalogFilePath: jsonCatalogFilePath,
    jsonFlightFilePath:  jsonFlightFilePath,
    // Phase 3 endpoint implementations
    fetchBodyData:         fetchBodyData,
    fetchPartsData:        fetchPartsData,
    fetchAscentData:       fetchAscentData,
    fetchMapData:          fetchMapData,
    fetchFltData:          fetchFltData,
    fetchMenuData:         fetchMenuData,
    fetchEventData:        fetchEventData,
    fetchCrewData:         fetchCrewData,
    fetchVesselOrbitData:  fetchVesselOrbitData,
    fetchVesselData:       fetchVesselData,
    fetchOpsData:          fetchOpsData
  };

}());
