// ksaDataService.js
// Phase 2 scaffolding: core infrastructure for the ASP → JSON.txt static-file migration.
// Phase 3 will add one fetch*() endpoint function per endpointimplementation order entry.
//
// Dependencies (must be loaded before this file):
//   helpFuncs.js  — provides dbResponse(), handleError()
//   ksaGlobals.js — provides KSA_UI_STATE.dataLoadQueue

// Wrap in an IIFE so internal helpers stay private; expose only the public API.
const KSA_DATA_SERVICE = (function () {
  'use strict';

  // ===========================================================================
  // CONSTANTS
  // ===========================================================================

  // Root-relative path to the JSON.txt file tree generated by convert_mdb_to_json.py.
  const DATABASE_ROOT = 'database/';

  // Parity-test debug logging.
  // Set  window.KSA_DS_DEBUG = true  in the browser console (before or after page load)
  // to log the assembled response string for each endpoint so it can be diffed against
  // the captured ASP response.  Usage:
  //   KSA_DS_DEBUG = true   ← enable
  //   KSA_DS_DEBUG = false  ← disable
  function _parity(label, responseText) {
    if (window.KSA_DS_DEBUG) {
      console.groupCollapsed('[KSA_DS parity] ' + label);
      console.log(responseText);
      console.groupEnd();
    }
  }

  // ===========================================================================
  // CACHE MAPS
  // ===========================================================================

  // Index cache: Map<entityId, indexObject>
  // indexObject keys are recordset folder names, values are sorted UT arrays.
  // e.g. { craftdata: [0, 28800], flightdata: [0, 28800, 57600], ... }
  const _indexCache = new Map();

  // Response cache: Map<url, parsedData>
  // Covers both UT-split record objects and bulk array files.
  // Keyed by the canonical URL (without cache-bust query string).
  const _responseCache = new Map();

  // In-flight deduplicator: Map<url, Promise<parsedData>>
  // Prevents duplicate concurrent fetch() calls for the same file.
  const _inFlight = new Map();

  // ===========================================================================
  // PRIVATE HELPERS
  // ===========================================================================

  // Returns "YYYY-MM-DD" so same-day requests share the browser cache but the
  // cache refreshes automatically the following day (mirrors loadJsonTxt behaviour).
  function _dateBust() {
    return new Date().toISOString().split('T')[0];
  }

  // ===========================================================================
  // PUBLIC API — CORE DATA UTILITIES
  // ===========================================================================

  /**
   * seekToUT(utArray, targetUT)
   *
   * Binary search: returns the largest UT value in a sorted ascending array that
   * is <= targetUT.  Replicates the ASP MoveLast/MovePrevious loop used across
   * all UT-seeking endpoints.
   *
   * If every element is > targetUT the first element is returned (mirrors ASP
   * behaviour where MovePrevious past BOF calls MoveNext back to first record).
   *
   * @param {number[]} utArray   Sorted ascending array of UT timestamps.
   * @param {number}   targetUT  The game-time UT to search for.
   * @returns {number|null}      Matching UT, or null if the array is empty.
   */
  function seekToUT(utArray, targetUT) {
    if (!utArray || !utArray.length) return null;
    var lo = 0, hi = utArray.length - 1, result = utArray[0];
    while (lo <= hi) {
      var mid = (lo + hi) >>> 1;
      if (utArray[mid] <= targetUT) {
        result = utArray[mid];
        lo = mid + 1;
      } else {
        hi = mid - 1;
      }
    }
    return result;
  }

  /**
   * getNextUT(utArray, targetUT)
   *
   * Binary search: returns the smallest UT value in a sorted ascending array
   * that is strictly > targetUT.  Used to pre-cache the next record boundary
   * (the "future data" the ASP endpoints also read ahead for).
   *
   * @param {number[]} utArray   Sorted ascending array of UT timestamps.
   * @param {number}   targetUT  The current game-time UT.
   * @returns {number|null}      The next UT after targetUT, or null if there are none.
   */
  function getNextUT(utArray, targetUT) {
    if (!utArray || !utArray.length) return null;
    var lo = 0, hi = utArray.length - 1, result = null;
    while (lo <= hi) {
      var mid = (lo + hi) >>> 1;
      if (utArray[mid] > targetUT) {
        result = utArray[mid];
        hi = mid - 1;
      } else {
        lo = mid + 1;
      }
    }
    return result;
  }

  /**
   * fetchJson(url)
   *
   * fetch() + JSON.parse() wrapper with:
   *   - Response caching  (no re-download for the lifetime of the page)
   *   - In-flight deduplication (concurrent callers share one pending fetch)
   *   - Date-based cache-busting (daily cache refresh; same-day requests reuse
   *     the browser HTTP cache — identical to loadJsonTxt's strategy)
   *
   * NOTE: loadJsonTxt() is intentionally reserved for the multi-object social
   * archive format; this function is used for all database JSON.txt files.
   *
   * @param {string} url  Relative or absolute path to the .json.txt file.
   * @returns {Promise}   Resolves to the parsed JSON value (object, array, …).
   */
  function fetchJson(url) {
    // Serve from in-memory cache on repeated calls.
    if (_responseCache.has(url)) {
      return Promise.resolve(_responseCache.get(url));
    }
    // Return the existing promise if a fetch is already in progress.
    if (_inFlight.has(url)) {
      return _inFlight.get(url);
    }

    var sep = url.indexOf('?') !== -1 ? '&' : '?';
    var fullUrl = url + sep + '_=' + _dateBust();

    var promise = fetch(fullUrl)
      .then(function (resp) {
        if (!resp.ok) {
          throw new Error('HTTP ' + resp.status + ' loading: ' + url);
        }
        return resp.text();
      })
      .then(function (text) {
        var data = JSON.parse(text);
        _responseCache.set(url, data);
        _inFlight.delete(url);
        return data;
      })
      ['catch'](function (err) {        // bracket notation avoids IE8 reserved-word parse error
        _inFlight.delete(url);
        throw err;
      });

    _inFlight.set(url, promise);
    return promise;
  }

  /**
   * objToRs(obj)
   *
   * Inverse of rsToObj() in helpFuncs.js.
   * Converts a plain object to the ASP-style delimited record string that the
   * existing AJAX callbacks (loadBodyAJAX, loadPartsAJAX, …) already know how
   * to parse — producing zero front-end display changes.
   *
   * Format:  "Field~value`Field2~value2`Field3~value3"
   *   - Fields are separated by backtick (`)
   *   - No trailing backtick (mirrors ASP's left(record, len(record)-1))
   *   - Null/undefined values produce "Field~" (empty after the ~)
   *   - Boolean values produce "Field~true" / "Field~false"
   *   - All other values are coerced to string via String()
   *
   * @param {Object|null} obj  Plain object with DB field names as keys.
   * @returns {string}
   */
  function objToRs(obj) {
    if (!obj) return '';
    var parts = [];
    Object.keys(obj).forEach(function (key) {
      // Mirrors ASP's replace(field.name, " ", "") — strip spaces from column names.
      var fieldName = key.replace(/ /g, '');
      var val = obj[key];
      if (val === null || val === undefined) {
        parts.push(fieldName + '~');
      } else {
        parts.push(fieldName + '~' + String(val));
      }
    });
    return parts.join('`');
  }

  /**
   * invokeCallback(label, callback, responseText, data)
   *
   * Simulates a completed loadDB() call so that existing AJAX callbacks receive
   * the same mock-xhttp object they expect and KSA_UI_STATE.dataLoadQueue is
   * managed identically to a real XMLHttpRequest round-trip.
   *
   * Delegates to dbResponse() (from helpFuncs.js) so queue removal and error
   * handling are both handled by the same code path as real AJAX.
   *
   * @param {string}   label        Descriptive label pushed onto dataLoadQueue
   *                                (takes the place of the ASP URL).
   * @param {function} callback     The existing AJAX callback (receives (xhttp, data)).
   * @param {string}   responseText The fully assembled delimited string.
   * @param {*}        [data]       Optional pass-through value (same as loadDB's third arg).
   */
  function invokeCallback(label, callback, responseText, data) {
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    dbResponse({ responseText: responseText }, label, callback, data);
  }

  // ===========================================================================
  // PUBLIC API — PATH HELPERS
  // ===========================================================================

  /**
   * indexPath(entityId)
   * URL to the index file for a craft or kerbal entity.
   * e.g. indexPath('jeb') → 'database/jeb/jeb_index.json.txt'
   */
  function indexPath(entityId) {
    return DATABASE_ROOT + entityId + '/' + entityId + '_index.json.txt';
  }

  /**
   * dbFilePath(entityId, recordset, ut)
   * URL to a specific UT-split record file.
   * e.g. dbFilePath('jeb', 'stats', 12345) → 'database/jeb/stats/jeb_stats_12345.json.txt'
   */
  function dbFilePath(entityId, recordset, ut) {
    return DATABASE_ROOT + entityId + '/' + recordset + '/' +
           entityId + '_' + recordset + '_' + ut + '.json.txt';
  }

  /**
   * bulkFilePath(entityId, recordset)
   * URL to a bulk (non-UT-split) data file loaded all at once.
   * e.g. bulkFilePath('jeb', 'missions') → 'database/jeb/jeb_missions.json.txt'
   */
  function bulkFilePath(entityId, recordset) {
    return DATABASE_ROOT + entityId + '/' + entityId + '_' + recordset + '.json.txt';
  }

  /**
   * catalogFilePath(name)
   * URL to a _Catalogs file.
   * e.g. catalogFilePath('bodies') → 'database/_Catalogs/bodies.json.txt'
   */
  function catalogFilePath(name) {
    return DATABASE_ROOT + '_Catalogs/' + name + '.json.txt';
  }

  /**
   * flightFilePath(flightId, recordset)
   * URL to a _Flights data file (dbFlt* databases).
   * e.g. flightFilePath('someFlight', 'missiondata')
   *        → 'database/_Flights/someFlight/someFlight_missiondata.json.txt'
   */
  function flightFilePath(flightId, recordset) {
    return DATABASE_ROOT + '_Flights/' + flightId + '/' +
           flightId + '_' + recordset + '.json.txt';
  }

  // ===========================================================================
  // PUBLIC API — INDEX MANAGEMENT
  // ===========================================================================

  /**
   * loadIndex(entityId)
   *
   * Loads and caches the index file for a craft or kerbal entity (once per page
   * load).  Subsequent calls for the same entityId are served from the index
   * cache with no network round-trip.
   *
   * The index object maps recordset folder names to sorted UT arrays:
   *   { craftdata: [0, 28800], flightdata: [0, 28800, 57600], ... }
   *
   * @param {string} entityId  Craft DB name or kerbal ID (lowercase).
   * @returns {Promise<Object>}
   */
  function loadIndex(entityId) {
    if (_indexCache.has(entityId)) {
      return Promise.resolve(_indexCache.get(entityId));
    }
    return fetchJson(indexPath(entityId)).then(function (index) {
      _indexCache.set(entityId, index);
      return index;
    });
  }

  // ===========================================================================
  // PHASE 3 ENDPOINT IMPLEMENTATIONS
  // ===========================================================================

  // ---------------------------------------------------------------------------
  // Endpoint #1 — replaces loadBodyData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchBodyData(callback)
   *
   * Loads all planet and moon records from the merged bodies catalog and delivers
   * them to the existing loadBodyAJAX callback in the same pipe-delimited format
   * that loadBodyData.asp produced.
   *
   * ASP logic replicated: dump all records from Planets table then Moons table,
   * each as "Field~value`Field~value…|".  The JSON.txt file was built with the
   * same ordering (planets first, then moons), so no sorting is required here.
   *
   * @param {function} callback  Existing AJAX callback (loadBodyAJAX).
   */
  function fetchBodyData(callback) {
    var label = 'loadBodyData.asp';
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    fetchJson(catalogFilePath('bodies'))
      .then(function (records) {
        // Build the same pipe-delimited, backtick-separated string the ASP endpoint emitted.
        // Each record ends with "|"; loadBodyAJAX splits by "|" and filters empty strings.
        var rs = records.map(function (obj) { return objToRs(obj); }).join('|') + '|';
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #2 — replaces loadPartsData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchPartsData(callback)
   *
   * Loads all parts records from the parts catalog and delivers them to the
   * existing loadPartsAJAX callback in the same caret-delimited format that
   * loadPartsData.asp produced.
   *
   * ASP logic replicated: dump all records from the parts table, each as
   * "Field~value`Field~value…", joined by "^".  No trailing "^" — the ASP
   * endpoint strips it with left(output, len(output)-1) and loadPartsAJAX
   * splits on "^" without filtering empty strings, so a trailing delimiter
   * would push a null entry into KSA_CATALOGS.partsCatalog.
   *
   * @param {function} callback  Existing AJAX callback (loadPartsAJAX).
   */
  function fetchPartsData(callback) {
    var label = 'loadPartsData.asp';
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    fetchJson(catalogFilePath('parts'))
      .then(function (records) {
        // Join records with "^" — no trailing delimiter (matches ASP output).
        var rs = records.map(function (obj) { return objToRs(obj); }).join('^');
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #3 — replaces loadAscentData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchAscentData(db, callback)
   *
   * Loads all rows from the ascent data bulk file for a given craft and delivers
   * them to the existing loadAscentAJAX callback in the same pipe-delimited
   * format that loadAscentData.asp produced.
   *
   * ASP logic replicated:
   *   - Dump all records from the [ascent data] table.
   *   - Apply replace(field.name, " ", "") to strip spaces from field names
   *     (the only affected field is "Total Fuel" → "TotalFuel").
   *   - Join records with "|" — no trailing "|" (loadAscentAJAX does not
   *     filter empty strings after splitting, so a trailing delimiter would
   *     push a spurious empty object into ops.ascentData.telemetry).
   *
   * The bulk file is cached after the first fetch so repeated calls (e.g.
   * if the user navigates away and back to the same vessel) are free.
   *
   * @param {string}   db        Craft DB name (e.g. "ascensionmk2-2").
   * @param {function} callback  Existing AJAX callback (loadAscentAJAX).
   */
  function fetchAscentData(db, callback) {
    var label = 'loadAscentData.asp?db=' + db;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    fetchJson(bulkFilePath(db, 'ascentdata'))
      .then(function (records) {
        // ASP applied replace(field.name, " ", "") to strip spaces from column
        // names before writing them into the response string.  The only ascent
        // data field affected is "Total Fuel" → "TotalFuel", which the front-end
        // reads as .TotalFuel.  Normalise all keys defensively.
        var rs = records.map(function (obj) {
          var normalized = {};
          Object.keys(obj).forEach(function (k) {
            normalized[k.replace(/ /g, '')] = obj[k];
          });
          return objToRs(normalized);
        }).join('|');
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #4 — replaces loadMapData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchMapData(refID, callback)
   *
   * Loads map data from the maps catalog and delivers it to the existing callback
   * in the same format that loadMapData.asp produced.
   *
   * Two modes, mirroring the ASP:
   *   refID === -1  — return ALL records joined with "^" (no trailing "^").
   *                   Callback (loadSurfaceUpdatesAJAX) splits on "^" and calls
   *                   rsToObj() on each piece.
   *   refID number  — return the single record whose RefID matches.
   *                   Callback (loadMapDataAJAX) calls rsToObj() directly.
   *   Either mode   — returns "null" if no matching records exist.
   *
   * The maps catalog is loaded only once per page session; subsequent calls
   * (typically the per-body load triggered by ksaSurfaceOps) hit the fetchJson
   * response cache and filter in-memory — zero extra network round-trips.
   *
   * @param {number}   refID     -1 for all records, or the numeric body RefID.
   * @param {function} callback  Existing AJAX callback (loadSurfaceUpdatesAJAX
   *                             for refID=-1, loadMapDataAJAX for a specific body).
   */
  function fetchMapData(refID, callback) {
    var label = 'loadMapData.asp?refID=' + refID;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    fetchJson(catalogFilePath('maps'))
      .then(function (records) {
        var rs;
        if (refID === -1) {
          // Return all records joined with '^' — no trailing delimiter.
          if (!records || !records.length) {
            rs = 'null';
          } else {
            rs = records.map(function (obj) { return objToRs(obj); }).join('^');
          }
        } else {
          // Return only the one record whose RefID matches the requested body.
          var match = null;
          for (var i = 0; i < records.length; i++) {
            if (records[i].RefID === refID) { match = records[i]; break; }
          }
          rs = match ? objToRs(match) : 'null';
        }
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #5 — replaces loadFltData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchFltData(name, callback)
   *
   * Loads mission data (single record) and flight data (full array) for an
   * aircraft-type flight from the _Flights folder, then delivers them to the
   * existing loadFltDataAJAX callback in the same format that loadFltData.asp
   * produced.
   *
   * ASP logic replicated:
   *   - Dump the single [mission data] record as field~value pairs.
   *   - Iterate [flight data] sampling every 5th row (rsFlightData.move 5),
   *     joining sampled rows with "|" (no trailing "|").
   *   - Assemble as: <missionRs>^<sampledFlightRows>^<name>
   *
   * Both files are cached by fetchJson() after the first load, so subsequent
   * calls for the same flight (e.g. multi-flight loads) are served from memory.
   *
   * NOTE: The full flightdata file (~21K rows for a long flight) is downloaded
   * on the first request even though only every 5th row is used.  This is 5×
   * the data the ASP endpoint transmitted, but the cache makes repeat calls
   * free and preserves the full-resolution data for any future zoom feature.
   *
   * @param {string}   name      Flight DB name (e.g. "Deuce1-22-19").
   * @param {function} callback  Existing AJAX callback (loadFltDataAJAX).
   */
  function fetchFltData(name, callback) {
    var label = 'loadFltData.asp?data=' + name;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    Promise.all([
      fetchJson(flightFilePath(name, 'missiondata')),
      fetchJson(flightFilePath(name, 'flightdata'))
    ]).then(function (results) {
      var missionRecord   = results[0];   // plain object (single-record table)
      var allFlightRows   = results[1];   // array of all flight data records

      // Mission segment: single record → RS string.
      var missionRs = objToRs(missionRecord);

      // Flight segment: sample every 5th row, mirroring ASP's rsFlightData.move 5.
      // Indices 0, 5, 10, … — last included index is the largest multiple of 5
      // that does not exceed allFlightRows.length - 1 (same as ASP loop behaviour).
      var sampledRows = [];
      for (var i = 0; i < allFlightRows.length; i += 5) {
        sampledRows.push(objToRs(allFlightRows[i]));
      }
      var flightRs = sampledRows.join('|');

      // Final format: <missionRs>^<flightRs>^<name>
      var rs = missionRs + '^' + flightRs + '^' + name;
      _parity(label, rs);
      dbResponse({ responseText: rs }, label, callback);
    })
    ['catch'](function (err) {
      var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
      if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
      handleError(err, label, true);
    });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #6 — replaces loadMenuData.asp
  // ---------------------------------------------------------------------------

  /**
   * _buildMenuCraftRecord(vessel, ut)
   *
   * Private helper used only by fetchMenuData.
   * Computes the current SOI ref for a vessel at the given UT and, if the
   * vessel should appear in the menu (ref !== -2), assembles its record string.
   *
   * Returns null when ref === -2 (vessel is hidden from both menu lists).
   *
   * Format: DB~Vessel~SOI~Type~start~end~program~vesselName[~timeline]
   *
   * start default (MissionStartTime is null): FIRST SOI entry UT.
   *   NOTE: The original ASP used the LAST SOI entry UT for BOTH start and
   *   end defaults (defaultTime covered both).  The DB Reference now specifies
   *   start = first SOI entry UT, end = last SOI entry UT, which is what this
   *   function implements.  Revert to lastSoiUT if the old behaviour is needed.
   *
   * end default (MissionEnd is null): LAST SOI entry UT.
   */
  function _buildMenuCraftRecord(vessel, ut) {
    // Determine current SOI reference: last SOI entry whose timestamp <= ut.
    var ref = 0;
    var locations = vessel.SOI.split('|');
    for (var i = 0; i < locations.length; i++) {
      var parts = locations[i].split(';');
      if (parseFloat(parts[0]) <= ut) {
        ref = parseFloat(parts[1]);
      }
    }

    // ref === -2 → vessel is completely removed from both menu lists.
    if (ref === -2) return null;

    // Derive default times from SOI string.
    var firstSoiUT = parseFloat(locations[0].split(';')[0]);
    var lastSoiUT  = parseFloat(locations[locations.length - 1].split(';')[0]);

    var start = (vessel.MissionStartTime !== null && vessel.MissionStartTime !== undefined)
      ? vessel.MissionStartTime
      : firstSoiUT;  // Was: lastSoiUT — see note above.

    var end;
    if (vessel.MissionEnd !== null && vessel.MissionEnd !== undefined) {
      // MissionEnd format: "UTShow;UTEnd;Text" — extract UTEnd (index 1).
      end = vessel.MissionEnd.split(';')[1];
    } else {
      end = lastSoiUT;
    }

    // Program and vessel-patch names from Patches string.
    // Patches format: "Program;PatchURL;PageURL|VesselName;PatchURL[;PageURL]"
    var program, vesselName;
    if (vessel.Patches !== null && vessel.Patches !== undefined) {
      var patchParts = vessel.Patches.split('|');
      program    = patchParts[0].split(';')[0];
      vesselName = patchParts[1].split(';')[0];
    } else {
      program    = 'null';
      vesselName = 'null';
    }

    var record = vessel.DB     + '~' +
                 vessel.Vessel + '~' +
                 vessel.SOI    + '~' +
                 vessel.Type   + '~' +
                 start         + '~' +
                 end           + '~' +
                 program       + '~' +
                 vesselName;

    // Timeline is only appended when not null (matches ASP conditional).
    if (vessel.Timeline !== null && vessel.Timeline !== undefined) {
      record += '~' + vessel.Timeline;
    }

    return record;
  }

  /**
   * fetchMenuData(ut, callback)
   *
   * Loads the vessels and crew catalogs, UT-seeks each crew member's stats
   * record, and delivers the combined response to the existing loadMenuAJAX
   * callback in the same format that loadMenuData.asp produced.
   *
   * ASP logic replicated:
   *   Craft segment:
   *     - Compute current SOI ref for each vessel at the given UT (last SOI
   *       entry whose timestamp <= UT wins; default ref=0 if none match).
   *     - Omit vessels where ref === -2.
   *     - See _buildMenuCraftRecord() for per-record field details.
   *     - Join records with "*" (no trailing "*").
   *   Crew segment:
   *     - UT-seek each crew member's kerbal stats table via their index file.
   *     - Emit: FullName~Status~Rank~Assignment~Kerbal~UT~[Deactivation]~[Timeline]
   *       Deactivation is always emitted (empty string when null, matching
   *       ASP's unconditional response.write("~")).
   *       Timeline is only emitted when not null.
   *     - Join records with "|" (no trailing "|").
   *   Full response: <craftSegment>^<crewSegment>
   *
   * This is the primary startup-critical endpoint: after it resolves,
   * loadMenuAJAX bootstraps the sidebar and triggers loadOpsDataAJAX for
   * all active entities.  Catalogs and kerbal index files are cached by
   * fetchJson/loadIndex so they are free on subsequent calls.
   *
   * @param {number}   ut        Current game UT in seconds.
   * @param {function} callback  Existing AJAX callback (loadMenuAJAX).
   */
  function fetchMenuData(ut, callback) {
    var label = 'loadMenuData.asp?UT=' + ut;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);

    Promise.all([
      fetchJson(catalogFilePath('vessels')),
      fetchJson(catalogFilePath('crew'))
    ]).then(function (catalogs) {
      var vesselCatalog = catalogs[0];
      var crewCatalog   = catalogs[1];

      // For each crew member: load index → seekToUT in stats array → load stats.
      var crewPromises = crewCatalog.map(function (crewItem) {
        return loadIndex(crewItem.Kerbal).then(function (index) {
          var statsUT = seekToUT(index.stats, ut);
          return fetchJson(dbFilePath(crewItem.Kerbal, 'stats', statsUT))
            .then(function (statsRecord) {
              return { crewItem: crewItem, stats: statsRecord };
            });
        });
      });

      return Promise.all(crewPromises).then(function (crewResults) {
        return { vessels: vesselCatalog, crew: crewResults };
      });
    }).then(function (data) {

      // --- Craft segment ---
      var craftParts = [];
      data.vessels.forEach(function (vessel) {
        var rec = _buildMenuCraftRecord(vessel, ut);
        if (rec !== null) craftParts.push(rec);
      });

      // --- Crew segment ---
      var crewParts = data.crew.map(function (result) {
        var c = result.crewItem;
        var s = result.stats;

        var rec = c.FullName + '~' +
                  s.Status   + '~' +
                  s.Rank     + '~' +
                  (s.Assignment !== null && s.Assignment !== undefined ? String(s.Assignment) : '') + '~' +
                  c.Kerbal   + '~' +
                  s.UT;

        // Deactivation always written (empty string when null — ASP always
        // called response.write("~") for this field regardless of null).
        rec += '~' + (c.Deactivation !== null && c.Deactivation !== undefined
          ? c.Deactivation
          : '');

        // Timeline only written when not null.
        if (c.Timeline !== null && c.Timeline !== undefined) {
          rec += '~' + c.Timeline;
        }

        return rec;
      });

      var rs = craftParts.join('*') + '^' + crewParts.join('|');
      _parity(label, rs);
      dbResponse({ responseText: rs }, label, callback);
    })['catch'](function (err) {
      var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
      if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
      handleError(err, label, true);
    });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #7 — replaces loadEventData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchEventData(ut, callback)
   *
   * Scans all active, non-aircraft vessels for upcoming launch events and
   * planned maneuvers, then delivers the combined list to the existing
   * loadEventsAJAX callback in the same format that loadEventData.asp produced.
   *
   * ASP logic replicated:
   *   - Iterate vessels catalog (same order as Crafts recordset).
   *   - For each vessel, compute current SOI ref (last SOI entry UT <= ut).
   *     Default ref = -1 (vessel not yet active); skip if ref <= -1 or type === 'aircraft'.
   *   - Load launch times bulk file: collect ALL rows as launch entries.
   *     LaunchTime null → 0 (matches ASP's null-coercion).
   *   - Load index → seekToUT on flightplan array → load record: if ExecuteUT > ut,
   *     collect as a maneuver entry.
   *   - Launches: joined with "|" + "^" header (or "null|null^" when empty).
   *   - Maneuvers: first two entries joined with "|" (or "null" when absent).
   *   - No post-collection sort (SortArray is defined in the ASP but never called).
   *
   * The vessels catalog is already in _responseCache after fetchMenuData, so the
   * catalog fetch is free.  Launch times and index files are cached after first
   * load, making repeated fetchEventData calls (liftoff refresh, maneuver refresh)
   * serve fully from the in-memory caches.
   *
   * Entry formats:
   *   Launch:   UT;LaunchTime;DB;Vessel;Desc
   *   Maneuver: UT;ExecuteUT;DB;Vessel;Desc
   *
   * @param {number}   ut        Current game UT in seconds.
   * @param {function} callback  Existing AJAX callback (loadEventsAJAX).
   */
  function fetchEventData(ut, callback) {
    var label = 'loadEventData.asp?UT=' + ut;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);

    fetchJson(catalogFilePath('vessels'))
      .then(function (vessels) {

        // Process all vessels concurrently, preserving catalog iteration order.
        var vesselPromises = vessels.map(function (vessel) {

          // Compute current SOI ref.
          // ASP defaults to -1 (vessel not yet active); differs from fetchMenuData
          // which defaults to 0 — that difference is intentional and correct here.
          var ref = -1;
          var locations = vessel.SOI.split('|');
          for (var i = 0; i < locations.length; i++) {
            var parts = locations[i].split(';');
            if (parseFloat(parts[0]) <= ut) {
              ref = parseFloat(parts[1]);
            }
          }

          // Skip inactive (ref <= -1 covers -2 as well) and aircraft vessels.
          if (ref <= -1 || vessel.Type === 'aircraft') {
            return Promise.resolve({ launches: [], flightplan: null });
          }

          var db = vessel.DB;

          // Load launch times and index concurrently; both errors treated as
          // "no data" so a missing file never aborts the whole response.
          var launchPromise = fetchJson(bulkFilePath(db, 'launchtimes'))
            ['catch'](function () { return []; });

          var flightplanPromise = loadIndex(db)
            .then(function (index) {
              if (!index.flightplan || !index.flightplan.length) return null;
              var fpUT = seekToUT(index.flightplan, ut);
              if (fpUT === null) return null;
              return fetchJson(dbFilePath(db, 'flightplan', fpUT))
                ['catch'](function () { return null; });
            })
            ['catch'](function () { return null; });

          return Promise.all([launchPromise, flightplanPromise])
            .then(function (results) {
              var launchRows = results[0] || [];
              var fpRecord   = results[1];

              // Launch entries: one per row in the launch times table.
              // LaunchTime null → 0 (replicates ASP's null-coercion).
              var launchEntries = launchRows.map(function (row) {
                var lt = (row.LaunchTime !== null && row.LaunchTime !== undefined)
                  ? row.LaunchTime
                  : 0;
                return row.UT + ';' + lt + ';' + vessel.DB + ';' +
                       vessel.Vessel + ';' + vessel.Desc;
              });

              // Flightplan entry: only if ExecuteUT is still in the future.
              var fpEntry = null;
              if (fpRecord && fpRecord.ExecuteUT > ut) {
                fpEntry = fpRecord.UT + ';' + fpRecord.ExecuteUT + ';' +
                          vessel.DB + ';' + vessel.Vessel + ';' + fpRecord.Desc;
              }

              return { launches: launchEntries, flightplan: fpEntry };
            });
        });

        return Promise.all(vesselPromises);
      })
      .then(function (vesselResults) {

        // Collect launches and maneuvers in catalog-iteration order (no sort —
        // ASP defines SortArray but never calls it before the output section).
        var allLaunches  = [];
        var allManeuvers = [];
        vesselResults.forEach(function (result) {
          result.launches.forEach(function (entry) { allLaunches.push(entry); });
          if (result.flightplan !== null) allManeuvers.push(result.flightplan);
        });

        // Assemble response string (matches ASP output format exactly).
        //   Launches:  "e1|e2|…^"   or "null|null^" when empty
        //   Maneuvers: "m0|m1"      where absent slots become "null"
        var launchesStr = allLaunches.length > 0
          ? allLaunches.join('|')
          : 'null|null';

        var maneuver0 = allManeuvers.length > 0 ? allManeuvers[0] : 'null';
        var maneuver1 = allManeuvers.length > 1 ? allManeuvers[1] : 'null';

        var rs = launchesStr + '^' + maneuver0 + '|' + maneuver1;
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #8 — replaces loadCrewData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchCrewData(db, ut, callback)
   *
   * Loads all data for a single crew member and delivers it to the existing
   * loadCrewAJAX callback in the same format that loadCrewData.asp produced.
   *
   * ASP logic replicated:
   *   Catalog section  — all fields from the Crew table for the given kerbal.
   *   Stats section    — UT-seek: largest UT <= current from [kerbal stats].
   *   Missions section — all mission rows with UT <= current, pipe-delimited;
   *                      "null" when empty or first row is in the future.
   *   Ribbons section  — same filter pattern as missions.
   *   Background section — UT-seek: largest UT <= current from [background].
   *   Future section   — next stats record, next mission, next ribbon, next
   *                      background (each "null" when none exists).
   *
   * The crew catalog is already cached in _responseCache after fetchMenuData
   * runs at startup, so that fetch is always a cache hit.  The kerbal index
   * is likewise cached after fetchMenuData pre-loaded it for the menu.
   *
   * Response format (separators):
   *   [catalog]*[stats]^[missions]^[ribbons]^[background]*
   *   [nextStats]^[nextMission]^[nextRibbon]^[nextBackground]
   *
   * @param {string}   db        Kerbal database ID (lowercase, e.g. "jeb").
   * @param {number}   ut        Current game UT in seconds.
   * @param {function} callback  Existing AJAX callback (loadCrewAJAX).
   */
  function fetchCrewData(db, ut, callback) {
    var label = 'loadCrewData.asp?db=' + db + '&ut=' + ut;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);

    // Catalog (cache hit after fetchMenuData), index, and bulk files in parallel.
    Promise.all([
      fetchJson(catalogFilePath('crew')),
      loadIndex(db),
      fetchJson(bulkFilePath(db, 'missions'))['catch'](function () { return []; }),
      fetchJson(bulkFilePath(db, 'ribbons'))['catch'](function () { return []; })
    ]).then(function (results) {
      var crewCatalog = results[0];
      var index       = results[1];
      var allMissions = results[2];
      var allRibbons  = results[3];

      // Locate this kerbal's catalog entry (compare against Kerbal field, not DB).
      var crewEntry = crewCatalog.find(function (c) { return c.Kerbal === db; });

      // UT-seek for current and next stats / background.
      var statsUT    = seekToUT(index.stats,      ut);
      var bgUT       = seekToUT(index.background, ut);
      var nextStatsUT = getNextUT(index.stats,      ut);
      var nextBgUT    = getNextUT(index.background, ut);

      // Fetch current + next stats and background files concurrently.
      return Promise.all([
        fetchJson(dbFilePath(db, 'stats',      statsUT)),
        fetchJson(dbFilePath(db, 'background', bgUT)),
        nextStatsUT !== null
          ? fetchJson(dbFilePath(db, 'stats', nextStatsUT))['catch'](function () { return null; })
          : Promise.resolve(null),
        nextBgUT !== null
          ? fetchJson(dbFilePath(db, 'background', nextBgUT))['catch'](function () { return null; })
          : Promise.resolve(null)
      ]).then(function (fetched) {
        return {
          crewEntry:   crewEntry,
          stats:       fetched[0],
          background:  fetched[1],
          nextStats:   fetched[2],
          nextBg:      fetched[3],
          allMissions: allMissions,
          allRibbons:  allRibbons
        };
      });
    }).then(function (d) {

      // --- Catalog ---
      var catalogRs = objToRs(d.crewEntry);

      // --- Current stats ---
      var statsRs = objToRs(d.stats);

      // --- Missions up to current UT ---
      var currentMissions = d.allMissions.filter(function (m) { return m.UT <= ut; });
      var missionsRs = currentMissions.length > 0
        ? currentMissions.map(objToRs).join('|')
        : 'null';

      // --- Ribbons up to current UT ---
      var currentRibbons = d.allRibbons.filter(function (r) { return r.UT <= ut; });
      var ribbonsRs = currentRibbons.length > 0
        ? currentRibbons.map(objToRs).join('|')
        : 'null';

      // --- Current background ---
      var bgRs = objToRs(d.background);

      // --- Future records ---
      var nextStatsRs   = d.nextStats ? objToRs(d.nextStats) : 'null';
      var nextMission   = d.allMissions.find(function (m) { return m.UT > ut; });
      var nextMissionRs = nextMission ? objToRs(nextMission) : 'null';
      var nextRibbon    = d.allRibbons.find(function (r) { return r.UT > ut; });
      var nextRibbonRs  = nextRibbon ? objToRs(nextRibbon) : 'null';
      var nextBgRs      = d.nextBg ? objToRs(d.nextBg) : 'null';

      // Assemble: [catalog]*[stats]^[missions]^[ribbons]^[background]*
      //           [nextStats]^[nextMission]^[nextRibbon]^[nextBackground]
      var rs = catalogRs + '*' +
               statsRs + '^' + missionsRs + '^' + ribbonsRs + '^' + bgRs +
               '*' +
               nextStatsRs + '^' + nextMissionRs + '^' + nextRibbonRs + '^' + nextBgRs;

      _parity(label, rs);
      dbResponse({ responseText: rs }, label, callback);
    })['catch'](function (err) {
      var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
      if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
      handleError(err, label, true);
    });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #9 — replaces loadVesselOrbitData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchVesselOrbitData(db, ut, callback, data)
   *
   * UT-seeks the flight data and flightplan tables for a vessel and delivers
   * them to the existing addOrbitAJAX / loadVesselOrbitAJAX callback in the
   * same format that loadVesselOrbitData.asp produced.
   *
   * ASP logic replicated:
   *   - Open the individual craft DB (equivalent: load its index file).
   *   - UT-seek "flight data" table: find the record with the largest UT ≤ ut.
   *   - UT-seek "flightplan" table: same.
   *   - Output: db*[flightdataFields or "null"]|[flightplanFields or "null"]
   *   - Trailing backtick stripped from each segment (handled by objToRs).
   *
   * Cache behaviour: if the index was already loaded by fetchVesselData (#10),
   * this call is fully served from the in-memory caches with zero network
   * round-trips.
   *
   * @param {string}   db        Vessel DB name (e.g. "kerbin-II").
   * @param {number}   ut        Current game UT in seconds.
   * @param {function} callback  Existing AJAX callback (addOrbitAJAX or loadVesselOrbitAJAX).
   * @param {*}        [data]    Optional pass-through value (e.g. currObj for loadVesselOrbitAJAX).
   */
  function fetchVesselOrbitData(db, ut, callback, data) {
    var label = 'loadVesselOrbitData.asp?db=' + db + '&ut=' + ut;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);

    loadIndex(db)
      ['catch'](function () { return {}; })   // missing index → all-null response
      .then(function (index) {

        // UT-seek each table; null when the table has no entries in the index.
        var fdUT = (index.flightdata && index.flightdata.length)
          ? seekToUT(index.flightdata, ut)
          : null;
        var fpUT = (index.flightplan && index.flightplan.length)
          ? seekToUT(index.flightplan, ut)
          : null;

        var fdPromise = fdUT !== null
          ? fetchJson(dbFilePath(db, 'flightdata', fdUT))['catch'](function () { return null; })
          : Promise.resolve(null);

        var fpPromise = fpUT !== null
          ? fetchJson(dbFilePath(db, 'flightplan', fpUT))['catch'](function () { return null; })
          : Promise.resolve(null);

        return Promise.all([fdPromise, fpPromise]);
      })
      .then(function (results) {
        var fdRecord = results[0];
        var fpRecord = results[1];

        // Build segments: objToRs produces no trailing backtick, matching ASP's
        // left(output, len(output)-1) strip before each "|".
        var fdRs = fdRecord ? objToRs(fdRecord) : 'null';
        var fpRs = fpRecord ? objToRs(fpRecord) : 'null';

        var rs = db + '*' + fdRs + '|' + fpRs;
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback, data);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #10 — replaces loadVesselData.asp
  // ---------------------------------------------------------------------------

  /**
   * _boolStr(val)
   *
   * Private helper: converts a JS boolean (or boolean-like value) to a VBScript-
   * compatible string ("True" / "False") so parity-test diffs stay clean.
   * After parity is confirmed across all endpoints this can be changed to
   * lowercase ("true"/"false") in a single cleanup pass (see FC-2 in plan.md).
   */
  function _boolStr(val) {
    return val ? 'True' : 'False';
  }

  /**
   * fetchVesselData(db, ut, pastUT, callback, data)
   *
   * The most complex endpoint: loads all data tables for a single vessel and
   * delivers them to the existing loadVesselAJAX callback in the same format
   * that loadVesselData.asp produced.
   *
   * ASP logic replicated (in output order):
   *
   *   Header: "<db>Typ3"
   *
   *   Segment 0 — Catalog: all fields from the Crafts table for this vessel.
   *     Separator: "*"
   *
   *   Segment 1 — Ascent data range:
   *     "<firstUT>~<lastUT>"  when ascent data exists
   *     "false"               when the ascent data table is empty
   *     Separator: "*"
   *
   *   Segment 2 — Current record tables (caret-delimited):
   *     [craftdata]^[resources`NotNull~T/F]^[manifest]^[comms`NotNull~T/F]^[flightdata]^[ports]
   *     Each table: objToRs(record) or "null" when BOF (no record for this UT).
   *     Resources and comms uniquely add "`NotNull~True/False" after objToRs()
   *     (mirroring ASP's append-after-stripped-backtick pattern; see FC-3).
   *     Field names have spaces stripped (e.g. "Avg Velocity" → "AvgVelocity"),
   *     which objToRs() already does via replace(/ /g, '').
   *     Separator: "*"
   *
   *   Segment 3 — Event history (all craftdata records):
   *     "UT~CraftDescTitle|UT~CraftDescTitle|…"  (no trailing "|")
   *     Separator: "*"
   *
   *   Segment 4 — Launch times (all rows):
   *     "UT~LaunchTime|…"  or  "null"  when empty
   *     Separator: "*"
   *
   *   Segment 5 — Orbital period history (all flightdata records, up to last):
   *     "UT~OrbitalPeriod|…"  or  "null"  when empty
   *     (The last segment has no trailing "*" — stripped by ASP's final left())
   *
   * pastUT parameter: originally intended for history paging but the ASP code
   * comments it out as non-functional ("can't figure out what this was").
   * The fetch* implementation ignores it entirely (matches ASP behaviour).
   *
   * History section uses Option A (see FC-1 in plan.md): all craftdata and
   * flightdata files are fetched in parallel via Promise.all, then sorted by UT.
   * All results are cached by fetchJson so second loads within the session
   * are served from memory.
   *
   * @param {string}   db        Vessel DB name (e.g. "ascensionmk2-2").
   * @param {number}   ut        Current game UT in seconds.
   * @param {number}   pastUT    Ignored (non-functional in ASP; kept for signature parity).
   * @param {function} callback  Existing AJAX callback (loadVesselAJAX).
   * @param {*}        [data]    Optional pass-through value.
   */
  function fetchVesselData(db, ut, pastUT, callback, data) {
    var label = 'loadVesselData.asp?db=' + db + '&ut=' + ut;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);

    // Step 1: load catalog entry (cache hit after fetchMenuData) + vessel index.
    Promise.all([
      fetchJson(catalogFilePath('vessels')),
      loadIndex(db)['catch'](function () { return {}; }),
      fetchJson(bulkFilePath(db, 'ascentdata'))['catch'](function () { return []; }),
      fetchJson(bulkFilePath(db, 'launchtimes'))['catch'](function () { return []; })
    ]).then(function (step1) {
      var vesselCatalog = step1[0];
      var index         = step1[1];
      var ascentRows    = step1[2];
      var launchRows    = step1[3];

      // Locate this vessel's catalog entry.
      var catalogEntry = null;
      for (var vi = 0; vi < vesselCatalog.length; vi++) {
        if (vesselCatalog[vi].DB === db) { catalogEntry = vesselCatalog[vi]; break; }
      }

      // UT-seek for each of the 6 current-record tables.
      var cdUT  = (index.craftdata  && index.craftdata.length)  ? seekToUT(index.craftdata,  ut) : null;
      var resUT = (index.resources  && index.resources.length)  ? seekToUT(index.resources,  ut) : null;
      var mnUT  = (index.manifest   && index.manifest.length)   ? seekToUT(index.manifest,   ut) : null;
      var cmUT  = (index.comms      && index.comms.length)      ? seekToUT(index.comms,      ut) : null;
      var fdUT  = (index.flightdata && index.flightdata.length)  ? seekToUT(index.flightdata, ut) : null;
      var ptUT  = (index.ports      && index.ports.length)      ? seekToUT(index.ports,      ut) : null;
      // Future-guard: seekToUT returns utArray[0] when all elements > targetUT, but
      // ASP outputs "null" when its cursor reaches BOF before finding any UT <= targetUT.
      if (cdUT  !== null && cdUT  > ut) cdUT  = null;
      if (resUT !== null && resUT > ut) resUT = null;
      if (mnUT  !== null && mnUT  > ut) mnUT  = null;
      if (cmUT  !== null && cmUT  > ut) cmUT  = null;
      if (fdUT  !== null && fdUT  > ut) fdUT  = null;
      if (ptUT  !== null && ptUT  > ut) ptUT  = null;

      // Fetch all current-record files + all history files in parallel (Option A).
      // History: every craftdata file (for event list) + every flightdata file (for orbit history).
      var allCraftdataUTs  = (index.craftdata  || []);
      var allFlightdataUTs = (index.flightdata || []);

      var currentFetches = [
        cdUT  !== null ? fetchJson(dbFilePath(db, 'craftdata',  cdUT))['catch'](function () { return null; }) : Promise.resolve(null),
        resUT !== null ? fetchJson(dbFilePath(db, 'resources',  resUT))['catch'](function () { return null; }) : Promise.resolve(null),
        mnUT  !== null ? fetchJson(dbFilePath(db, 'manifest',   mnUT))['catch'](function () { return null; }) : Promise.resolve(null),
        cmUT  !== null ? fetchJson(dbFilePath(db, 'comms',      cmUT))['catch'](function () { return null; }) : Promise.resolve(null),
        fdUT  !== null ? fetchJson(dbFilePath(db, 'flightdata', fdUT))['catch'](function () { return null; }) : Promise.resolve(null),
        ptUT  !== null ? fetchJson(dbFilePath(db, 'ports',      ptUT))['catch'](function () { return null; }) : Promise.resolve(null)
      ];

      // History fetches: all craftdata and flightdata files.
      var historyFetches = allCraftdataUTs.map(function (hUT) {
        return fetchJson(dbFilePath(db, 'craftdata', hUT))['catch'](function () { return null; });
      });
      var orbitHistFetches = allFlightdataUTs.map(function (hUT) {
        return fetchJson(dbFilePath(db, 'flightdata', hUT))['catch'](function () { return null; });
      });

      return Promise.all(currentFetches.concat(historyFetches).concat(orbitHistFetches))
        .then(function (fetched) {
          var nHistory  = allCraftdataUTs.length;
          var nOrbitHis = allFlightdataUTs.length;

          return {
            catalogEntry:   catalogEntry,
            ascentRows:     ascentRows,
            launchRows:     launchRows,
            craftRecord:    fetched[0],
            resRecord:      fetched[1],
            mnRecord:       fetched[2],
            cmRecord:       fetched[3],
            fdRecord:       fetched[4],
            ptRecord:       fetched[5],
            allCraftdata:   fetched.slice(6, 6 + nHistory),
            allFlightdata:  fetched.slice(6 + nHistory, 6 + nHistory + nOrbitHis)
          };
        });
    }).then(function (d) {

      // --- Segment 0: catalog ---
      var catalogRs = objToRs(d.catalogEntry);

      // --- Segment 1: ascent data range ---
      var ascentSeg;
      if (d.ascentRows && d.ascentRows.length > 0) {
        ascentSeg = d.ascentRows[0].UT + '~' + d.ascentRows[d.ascentRows.length - 1].UT;
      } else {
        ascentSeg = 'false';
      }

      // --- Segment 2: current record tables (caret-delimited) ---

      // craftdata
      var cdRs = d.craftRecord ? objToRs(d.craftRecord) : 'null';

      // resources: append "`NotNull~True/False" — see FC-3 in plan.md.
      var resRs;
      if (d.resRecord) {
        var resNotNull = false;
        var resKeys = Object.keys(d.resRecord);
        for (var ri = 0; ri < resKeys.length; ri++) {
          var rk = resKeys[ri];
          if (rk !== 'UT' && d.resRecord[rk] !== null && d.resRecord[rk] !== undefined && d.resRecord[rk] !== '') {
            resNotNull = true; break;
          }
        }
        resRs = objToRs(d.resRecord) + '`NotNull~' + _boolStr(resNotNull);
      } else {
        resRs = 'null';
      }

      // manifest (crew) — plain objToRs, no NotNull
      var mnRs = d.mnRecord ? objToRs(d.mnRecord) : 'null';

      // comms: append "`NotNull~True/False".
      // ASP condition: field name !== "UT" OR field name !== "Connection" AND value !== ""
      // (note: the ASP uses OR which is always true for any field, effectively: any non-empty value → NotNull)
      // Functionally: if Comms field (the antenna string) is non-empty → True.
      var cmRs;
      if (d.cmRecord) {
        var cmNotNull = false;
        var cmKeys = Object.keys(d.cmRecord);
        for (var ci = 0; ci < cmKeys.length; ci++) {
          var ck = cmKeys[ci];
          if (d.cmRecord[ck] !== null && d.cmRecord[ck] !== undefined && d.cmRecord[ck] !== '') {
            cmNotNull = true; break;
          }
        }
        cmRs = objToRs(d.cmRecord) + '`NotNull~' + _boolStr(cmNotNull);
      } else {
        cmRs = 'null';
      }

      // flightdata (orbital data) — plain objToRs, no NotNull
      var fdRs = d.fdRecord ? objToRs(d.fdRecord) : 'null';

      // ports — plain objToRs, no NotNull
      var ptRs = d.ptRecord ? objToRs(d.ptRecord) : 'null';

      var tablesSeg = cdRs + '^' + resRs + '^' + mnRs + '^' + cmRs + '^' + fdRs + '^' + ptRs;

      // --- Segment 3: event history (all craftdata records, sorted by UT) ---
      // Filter nulls (failed fetches), sort by UT, then emit "UT~CraftDescTitle".
      var historyItems = d.allCraftdata
        .filter(function (r) { return r !== null; })
        .sort(function (a, b) { return a.UT - b.UT; });
      var historySeg = historyItems
        .map(function (r) { return r.UT + '~' + (r.CraftDescTitle || ''); })
        .join('|');

      // --- Segment 4: launch times (all rows) ---
      var launchSeg;
      if (d.launchRows && d.launchRows.length > 0) {
        launchSeg = d.launchRows
          .map(function (r) { return r.UT + '~' + (r.LaunchTime !== null && r.LaunchTime !== undefined ? r.LaunchTime : ''); })
          .join('|');
      } else {
        launchSeg = 'null';
      }

      // --- Segment 5: orbital period history (all flightdata records, sorted by UT) ---
      // "Orbital Period" field → stored as "Orbital Period" in JSON, stripped to "OrbitalPeriod"
      // by objToRs but here we only emit UT~Period pairs (not a full RS), so read directly.
      var orbitHistItems = d.allFlightdata
        .filter(function (r) { return r !== null; })
        .sort(function (a, b) { return a.UT - b.UT; });

      var orbitHistSeg;
      if (orbitHistItems.length > 0) {
        // Include ALL records — null Orbital Period emits as empty string ("UT~"),
        // matching VBScript's null-to-empty coercion in the ASP output (e.g. re-entry records).
        orbitHistSeg = orbitHistItems
          .map(function (r) {
            var period = (r['Orbital Period'] !== null && r['Orbital Period'] !== undefined)
              ? r['Orbital Period'] : '';
            return r.UT + '~' + period;
          })
          .join('|');
      } else {
        orbitHistSeg = 'null';
      }

      // Final assembly:
      // "<db>Typ3" + seg0 + "*" + seg1 + "*" + seg2 + "*" + seg3 + "*" + seg4 + "*" + seg5
      // (no trailing "*" — ASP's left(output, len(output)-1) strips it)
      var rs = db + 'Typ3' +
               catalogRs    + '*' +
               ascentSeg    + '*' +
               tablesSeg    + '*' +
               historySeg   + '*' +
               launchSeg    + '*' +
               orbitHistSeg;

      _parity(label, rs);
      dbResponse({ responseText: rs }, label, callback, data);
    })['catch'](function (err) {
      var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
      if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
      handleError(err, label, true);
    });
  }

  // ===========================================================================
  // EXPORTS
  // ===========================================================================

  return {
    // Core data utilities
    seekToUT:        seekToUT,
    getNextUT:       getNextUT,
    fetchJson:       fetchJson,
    objToRs:         objToRs,
    invokeCallback:  invokeCallback,
    // Index management
    loadIndex:       loadIndex,
    // Path helpers
    indexPath:       indexPath,
    dbFilePath:      dbFilePath,
    bulkFilePath:    bulkFilePath,
    catalogFilePath: catalogFilePath,
    flightFilePath:  flightFilePath,
    // Phase 3 endpoint implementations
    fetchBodyData:         fetchBodyData,
    fetchPartsData:        fetchPartsData,
    fetchAscentData:       fetchAscentData,
    fetchMapData:          fetchMapData,
    fetchFltData:          fetchFltData,
    fetchMenuData:         fetchMenuData,
    fetchEventData:        fetchEventData,
    fetchCrewData:         fetchCrewData,
    fetchVesselOrbitData:  fetchVesselOrbitData,
    fetchVesselData:       fetchVesselData
  };

}());
