// ksaDataService.js
// Phase 2 scaffolding: core infrastructure for the ASP → JSON.txt static-file migration.
// Phase 3 will add one fetch*() endpoint function per endpointimplementation order entry.
//
// Dependencies (must be loaded before this file):
//   helpFuncs.js  — provides dbResponse(), handleError()
//   ksaGlobals.js — provides KSA_UI_STATE.dataLoadQueue

// Wrap in an IIFE so internal helpers stay private; expose only the public API.
const KSA_DATA_SERVICE = (function () {
  'use strict';

  // ===========================================================================
  // CONSTANTS
  // ===========================================================================

  // Root-relative path to the JSON.txt file tree generated by convert_mdb_to_json.py.
  const DATABASE_ROOT = 'database/';

  // Parity-test debug logging.
  // Set  window.KSA_DS_DEBUG = true  in the browser console (before or after page load)
  // to log the assembled response string for each endpoint so it can be diffed against
  // the captured ASP response.  Usage:
  //   KSA_DS_DEBUG = true   ← enable
  //   KSA_DS_DEBUG = false  ← disable
  function _parity(label, responseText) {
    if (window.KSA_DS_DEBUG) {
      console.groupCollapsed('[KSA_DS parity] ' + label);
      console.log(responseText);
      console.groupEnd();
    }
  }

  // ===========================================================================
  // CACHE MAPS
  // ===========================================================================

  // Index cache: Map<entityId, indexObject>
  // indexObject keys are recordset folder names, values are sorted UT arrays.
  // e.g. { craftdata: [0, 28800], flightdata: [0, 28800, 57600], ... }
  const _indexCache = new Map();

  // Response cache: Map<url, parsedData>
  // Covers both UT-split record objects and bulk array files.
  // Keyed by the canonical URL (without cache-bust query string).
  const _responseCache = new Map();

  // In-flight deduplicator: Map<url, Promise<parsedData>>
  // Prevents duplicate concurrent fetch() calls for the same file.
  const _inFlight = new Map();

  // ===========================================================================
  // PRIVATE HELPERS
  // ===========================================================================

  // Returns "YYYY-MM-DD" so same-day requests share the browser cache but the
  // cache refreshes automatically the following day (mirrors loadJsonTxt behaviour).
  function _dateBust() {
    return new Date().toISOString().split('T')[0];
  }

  // ===========================================================================
  // PUBLIC API — CORE DATA UTILITIES
  // ===========================================================================

  /**
   * seekToUT(utArray, targetUT)
   *
   * Binary search: returns the largest UT value in a sorted ascending array that
   * is <= targetUT.  Replicates the ASP MoveLast/MovePrevious loop used across
   * all UT-seeking endpoints.
   *
   * If every element is > targetUT the first element is returned (mirrors ASP
   * behaviour where MovePrevious past BOF calls MoveNext back to first record).
   *
   * @param {number[]} utArray   Sorted ascending array of UT timestamps.
   * @param {number}   targetUT  The game-time UT to search for.
   * @returns {number|null}      Matching UT, or null if the array is empty.
   */
  function seekToUT(utArray, targetUT) {
    if (!utArray || !utArray.length) return null;
    var lo = 0, hi = utArray.length - 1, result = utArray[0];
    while (lo <= hi) {
      var mid = (lo + hi) >>> 1;
      if (utArray[mid] <= targetUT) {
        result = utArray[mid];
        lo = mid + 1;
      } else {
        hi = mid - 1;
      }
    }
    return result;
  }

  /**
   * getNextUT(utArray, targetUT)
   *
   * Binary search: returns the smallest UT value in a sorted ascending array
   * that is strictly > targetUT.  Used to pre-cache the next record boundary
   * (the "future data" the ASP endpoints also read ahead for).
   *
   * @param {number[]} utArray   Sorted ascending array of UT timestamps.
   * @param {number}   targetUT  The current game-time UT.
   * @returns {number|null}      The next UT after targetUT, or null if there are none.
   */
  function getNextUT(utArray, targetUT) {
    if (!utArray || !utArray.length) return null;
    var lo = 0, hi = utArray.length - 1, result = null;
    while (lo <= hi) {
      var mid = (lo + hi) >>> 1;
      if (utArray[mid] > targetUT) {
        result = utArray[mid];
        hi = mid - 1;
      } else {
        lo = mid + 1;
      }
    }
    return result;
  }

  /**
   * fetchJson(url)
   *
   * fetch() + JSON.parse() wrapper with:
   *   - Response caching  (no re-download for the lifetime of the page)
   *   - In-flight deduplication (concurrent callers share one pending fetch)
   *   - Date-based cache-busting (daily cache refresh; same-day requests reuse
   *     the browser HTTP cache — identical to loadJsonTxt's strategy)
   *
   * NOTE: loadJsonTxt() is intentionally reserved for the multi-object social
   * archive format; this function is used for all database JSON.txt files.
   *
   * @param {string} url  Relative or absolute path to the .json.txt file.
   * @returns {Promise}   Resolves to the parsed JSON value (object, array, …).
   */
  function fetchJson(url) {
    // Serve from in-memory cache on repeated calls.
    if (_responseCache.has(url)) {
      return Promise.resolve(_responseCache.get(url));
    }
    // Return the existing promise if a fetch is already in progress.
    if (_inFlight.has(url)) {
      return _inFlight.get(url);
    }

    var sep = url.indexOf('?') !== -1 ? '&' : '?';
    var fullUrl = url + sep + '_=' + _dateBust();

    var promise = fetch(fullUrl)
      .then(function (resp) {
        if (!resp.ok) {
          throw new Error('HTTP ' + resp.status + ' loading: ' + url);
        }
        return resp.text();
      })
      .then(function (text) {
        var data = JSON.parse(text);
        _responseCache.set(url, data);
        _inFlight.delete(url);
        return data;
      })
      ['catch'](function (err) {        // bracket notation avoids IE8 reserved-word parse error
        _inFlight.delete(url);
        throw err;
      });

    _inFlight.set(url, promise);
    return promise;
  }

  /**
   * objToRs(obj)
   *
   * Inverse of rsToObj() in helpFuncs.js.
   * Converts a plain object to the ASP-style delimited record string that the
   * existing AJAX callbacks (loadBodyAJAX, loadPartsAJAX, …) already know how
   * to parse — producing zero front-end display changes.
   *
   * Format:  "Field~value`Field2~value2`Field3~value3"
   *   - Fields are separated by backtick (`)
   *   - No trailing backtick (mirrors ASP's left(record, len(record)-1))
   *   - Null/undefined values produce "Field~" (empty after the ~)
   *   - Boolean values produce "Field~true" / "Field~false"
   *   - All other values are coerced to string via String()
   *
   * @param {Object|null} obj  Plain object with DB field names as keys.
   * @returns {string}
   */
  function objToRs(obj) {
    if (!obj) return '';
    var parts = [];
    Object.keys(obj).forEach(function (key) {
      var val = obj[key];
      if (val === null || val === undefined) {
        parts.push(key + '~');
      } else {
        parts.push(key + '~' + String(val));
      }
    });
    return parts.join('`');
  }

  /**
   * invokeCallback(label, callback, responseText, data)
   *
   * Simulates a completed loadDB() call so that existing AJAX callbacks receive
   * the same mock-xhttp object they expect and KSA_UI_STATE.dataLoadQueue is
   * managed identically to a real XMLHttpRequest round-trip.
   *
   * Delegates to dbResponse() (from helpFuncs.js) so queue removal and error
   * handling are both handled by the same code path as real AJAX.
   *
   * @param {string}   label        Descriptive label pushed onto dataLoadQueue
   *                                (takes the place of the ASP URL).
   * @param {function} callback     The existing AJAX callback (receives (xhttp, data)).
   * @param {string}   responseText The fully assembled delimited string.
   * @param {*}        [data]       Optional pass-through value (same as loadDB's third arg).
   */
  function invokeCallback(label, callback, responseText, data) {
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    dbResponse({ responseText: responseText }, label, callback, data);
  }

  // ===========================================================================
  // PUBLIC API — PATH HELPERS
  // ===========================================================================

  /**
   * indexPath(entityId)
   * URL to the index file for a craft or kerbal entity.
   * e.g. indexPath('jeb') → 'database/jeb/jeb_index.json.txt'
   */
  function indexPath(entityId) {
    return DATABASE_ROOT + entityId + '/' + entityId + '_index.json.txt';
  }

  /**
   * dbFilePath(entityId, recordset, ut)
   * URL to a specific UT-split record file.
   * e.g. dbFilePath('jeb', 'stats', 12345) → 'database/jeb/stats/jeb_stats_12345.json.txt'
   */
  function dbFilePath(entityId, recordset, ut) {
    return DATABASE_ROOT + entityId + '/' + recordset + '/' +
           entityId + '_' + recordset + '_' + ut + '.json.txt';
  }

  /**
   * bulkFilePath(entityId, recordset)
   * URL to a bulk (non-UT-split) data file loaded all at once.
   * e.g. bulkFilePath('jeb', 'missions') → 'database/jeb/jeb_missions.json.txt'
   */
  function bulkFilePath(entityId, recordset) {
    return DATABASE_ROOT + entityId + '/' + entityId + '_' + recordset + '.json.txt';
  }

  /**
   * catalogFilePath(name)
   * URL to a _Catalogs file.
   * e.g. catalogFilePath('bodies') → 'database/_Catalogs/bodies.json.txt'
   */
  function catalogFilePath(name) {
    return DATABASE_ROOT + '_Catalogs/' + name + '.json.txt';
  }

  /**
   * flightFilePath(flightId, recordset)
   * URL to a _Flights data file (dbFlt* databases).
   * e.g. flightFilePath('someFlight', 'missiondata')
   *        → 'database/_Flights/someFlight/someFlight_missiondata.json.txt'
   */
  function flightFilePath(flightId, recordset) {
    return DATABASE_ROOT + '_Flights/' + flightId + '/' +
           flightId + '_' + recordset + '.json.txt';
  }

  // ===========================================================================
  // PUBLIC API — INDEX MANAGEMENT
  // ===========================================================================

  /**
   * loadIndex(entityId)
   *
   * Loads and caches the index file for a craft or kerbal entity (once per page
   * load).  Subsequent calls for the same entityId are served from the index
   * cache with no network round-trip.
   *
   * The index object maps recordset folder names to sorted UT arrays:
   *   { craftdata: [0, 28800], flightdata: [0, 28800, 57600], ... }
   *
   * @param {string} entityId  Craft DB name or kerbal ID (lowercase).
   * @returns {Promise<Object>}
   */
  function loadIndex(entityId) {
    if (_indexCache.has(entityId)) {
      return Promise.resolve(_indexCache.get(entityId));
    }
    return fetchJson(indexPath(entityId)).then(function (index) {
      _indexCache.set(entityId, index);
      return index;
    });
  }

  // ===========================================================================
  // PHASE 3 ENDPOINT IMPLEMENTATIONS
  // ===========================================================================

  // ---------------------------------------------------------------------------
  // Endpoint #1 — replaces loadBodyData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchBodyData(callback)
   *
   * Loads all planet and moon records from the merged bodies catalog and delivers
   * them to the existing loadBodyAJAX callback in the same pipe-delimited format
   * that loadBodyData.asp produced.
   *
   * ASP logic replicated: dump all records from Planets table then Moons table,
   * each as "Field~value`Field~value…|".  The JSON.txt file was built with the
   * same ordering (planets first, then moons), so no sorting is required here.
   *
   * @param {function} callback  Existing AJAX callback (loadBodyAJAX).
   */
  function fetchBodyData(callback) {
    var label = 'loadBodyData.asp';
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    fetchJson(catalogFilePath('bodies'))
      .then(function (records) {
        // Build the same pipe-delimited, backtick-separated string the ASP endpoint emitted.
        // Each record ends with "|"; loadBodyAJAX splits by "|" and filters empty strings.
        var rs = records.map(function (obj) { return objToRs(obj); }).join('|') + '|';
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #2 — replaces loadPartsData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchPartsData(callback)
   *
   * Loads all parts records from the parts catalog and delivers them to the
   * existing loadPartsAJAX callback in the same caret-delimited format that
   * loadPartsData.asp produced.
   *
   * ASP logic replicated: dump all records from the parts table, each as
   * "Field~value`Field~value…", joined by "^".  No trailing "^" — the ASP
   * endpoint strips it with left(output, len(output)-1) and loadPartsAJAX
   * splits on "^" without filtering empty strings, so a trailing delimiter
   * would push a null entry into KSA_CATALOGS.partsCatalog.
   *
   * @param {function} callback  Existing AJAX callback (loadPartsAJAX).
   */
  function fetchPartsData(callback) {
    var label = 'loadPartsData.asp';
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    fetchJson(catalogFilePath('parts'))
      .then(function (records) {
        // Join records with "^" — no trailing delimiter (matches ASP output).
        var rs = records.map(function (obj) { return objToRs(obj); }).join('^');
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #3 — replaces loadAscentData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchAscentData(db, callback)
   *
   * Loads all rows from the ascent data bulk file for a given craft and delivers
   * them to the existing loadAscentAJAX callback in the same pipe-delimited
   * format that loadAscentData.asp produced.
   *
   * ASP logic replicated:
   *   - Dump all records from the [ascent data] table.
   *   - Apply replace(field.name, " ", "") to strip spaces from field names
   *     (the only affected field is "Total Fuel" → "TotalFuel").
   *   - Join records with "|" — no trailing "|" (loadAscentAJAX does not
   *     filter empty strings after splitting, so a trailing delimiter would
   *     push a spurious empty object into ops.ascentData.telemetry).
   *
   * The bulk file is cached after the first fetch so repeated calls (e.g.
   * if the user navigates away and back to the same vessel) are free.
   *
   * @param {string}   db        Craft DB name (e.g. "ascensionmk2-2").
   * @param {function} callback  Existing AJAX callback (loadAscentAJAX).
   */
  function fetchAscentData(db, callback) {
    var label = 'loadAscentData.asp?db=' + db;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    fetchJson(bulkFilePath(db, 'ascentdata'))
      .then(function (records) {
        // ASP applied replace(field.name, " ", "") to strip spaces from column
        // names before writing them into the response string.  The only ascent
        // data field affected is "Total Fuel" → "TotalFuel", which the front-end
        // reads as .TotalFuel.  Normalise all keys defensively.
        var rs = records.map(function (obj) {
          var normalized = {};
          Object.keys(obj).forEach(function (k) {
            normalized[k.replace(/ /g, '')] = obj[k];
          });
          return objToRs(normalized);
        }).join('|');
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ---------------------------------------------------------------------------
  // Endpoint #4 — replaces loadMapData.asp
  // ---------------------------------------------------------------------------
  /**
   * fetchMapData(refID, callback)
   *
   * Loads map data from the maps catalog and delivers it to the existing callback
   * in the same format that loadMapData.asp produced.
   *
   * Two modes, mirroring the ASP:
   *   refID === -1  — return ALL records joined with "^" (no trailing "^").
   *                   Callback (loadSurfaceUpdatesAJAX) splits on "^" and calls
   *                   rsToObj() on each piece.
   *   refID number  — return the single record whose RefID matches.
   *                   Callback (loadMapDataAJAX) calls rsToObj() directly.
   *   Either mode   — returns "null" if no matching records exist.
   *
   * The maps catalog is loaded only once per page session; subsequent calls
   * (typically the per-body load triggered by ksaSurfaceOps) hit the fetchJson
   * response cache and filter in-memory — zero extra network round-trips.
   *
   * @param {number}   refID     -1 for all records, or the numeric body RefID.
   * @param {function} callback  Existing AJAX callback (loadSurfaceUpdatesAJAX
   *                             for refID=-1, loadMapDataAJAX for a specific body).
   */
  function fetchMapData(refID, callback) {
    var label = 'loadMapData.asp?refID=' + refID;
    KSA_UI_STATE.dataLoadQueue.push(label);
    console.log('[KSA_DATA_SERVICE]', label);
    fetchJson(catalogFilePath('maps'))
      .then(function (records) {
        var rs;
        if (refID === -1) {
          // Return all records joined with '^' — no trailing delimiter.
          if (!records || !records.length) {
            rs = 'null';
          } else {
            rs = records.map(function (obj) { return objToRs(obj); }).join('^');
          }
        } else {
          // Return only the one record whose RefID matches the requested body.
          var match = null;
          for (var i = 0; i < records.length; i++) {
            if (records[i].RefID === refID) { match = records[i]; break; }
          }
          rs = match ? objToRs(match) : 'null';
        }
        _parity(label, rs);
        dbResponse({ responseText: rs }, label, callback);
      })
      ['catch'](function (err) {
        var idx = KSA_UI_STATE.dataLoadQueue.indexOf(label);
        if (idx > -1) KSA_UI_STATE.dataLoadQueue.splice(idx, 1);
        handleError(err, label, true);
      });
  }

  // ===========================================================================
  // EXPORTS
  // ===========================================================================

  return {
    // Core data utilities
    seekToUT:        seekToUT,
    getNextUT:       getNextUT,
    fetchJson:       fetchJson,
    objToRs:         objToRs,
    invokeCallback:  invokeCallback,
    // Index management
    loadIndex:       loadIndex,
    // Path helpers
    indexPath:       indexPath,
    dbFilePath:      dbFilePath,
    bulkFilePath:    bulkFilePath,
    catalogFilePath: catalogFilePath,
    flightFilePath:  flightFilePath,
    // Phase 3 endpoint implementations
    fetchBodyData:    fetchBodyData,
    fetchPartsData:   fetchPartsData,
    fetchAscentData:  fetchAscentData,
    fetchMapData:     fetchMapData
  };

}());
